const data = {
  "Data": {
    "odds": [{
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#1",
      "id": 0,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#2",
      "id": 1,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#3",
      "id": 2,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#4",
      "id": 3,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#5",
      "id": 4,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#6",
      "id": 5,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#7",
      "id": 6,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#8",
      "id": 7,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#9",
      "id": 8,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u51a0\u519b#10",
      "id": 9,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u51a0\u519b#\u5927",
      "id": 10,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u51a0\u519b#\u5c0f",
      "id": 11,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u51a0\u519b#\u5355",
      "id": 12,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u51a0\u519b#\u53cc",
      "id": 13,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "dragon",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u51a0\u519b#\u9f99",
      "id": 14,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first",
      "input_name": "tiger",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u51a0\u519b#\u864e",
      "id": 15,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#1",
      "id": 16,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#2",
      "id": 17,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#3",
      "id": 18,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#4",
      "id": 19,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#5",
      "id": 20,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#6",
      "id": 21,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#7",
      "id": 22,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#8",
      "id": 23,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#9",
      "id": 24,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u4e9a\u519b#10",
      "id": 25,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u4e9a\u519b#\u5927",
      "id": 26,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u4e9a\u519b#\u5c0f",
      "id": 27,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u4e9a\u519b#\u5355",
      "id": 28,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u4e9a\u519b#\u53cc",
      "id": 29,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "dragon",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u4e9a\u519b#\u9f99",
      "id": 30,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "second",
      "input_name": "tiger",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u4e9a\u519b#\u864e",
      "id": 31,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#1",
      "id": 32,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#2",
      "id": 33,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#3",
      "id": 34,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#4",
      "id": 35,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#5",
      "id": 36,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#6",
      "id": 37,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#7",
      "id": 38,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#8",
      "id": 39,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#9",
      "id": 40,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#10",
      "id": 41,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#\u5927",
      "id": 42,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#\u5c0f",
      "id": 43,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#\u5355",
      "id": 44,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#\u53cc",
      "id": 45,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "dragon",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#\u9f99",
      "id": 46,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "third",
      "input_name": "tiger",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u540d#\u864e",
      "id": 47,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#1",
      "id": 48,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#2",
      "id": 49,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#3",
      "id": 50,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#4",
      "id": 51,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#5",
      "id": 52,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#6",
      "id": 53,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#7",
      "id": 54,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#8",
      "id": 55,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#9",
      "id": 56,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#10",
      "id": 57,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#\u5927",
      "id": 58,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#\u5c0f",
      "id": 59,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#\u5355",
      "id": 60,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#\u53cc",
      "id": 61,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "dragon",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#\u9f99",
      "id": 62,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fourth",
      "input_name": "tiger",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u56db\u540d#\u864e",
      "id": 63,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#1",
      "id": 64,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#2",
      "id": 65,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#3",
      "id": 66,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#4",
      "id": 67,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#5",
      "id": 68,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#6",
      "id": 69,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#7",
      "id": 70,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#8",
      "id": 71,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#9",
      "id": 72,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#10",
      "id": 73,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#\u5927",
      "id": 74,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#\u5c0f",
      "id": 75,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#\u5355",
      "id": 76,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#\u53cc",
      "id": 77,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "dragon",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#\u9f99",
      "id": 78,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "fifth",
      "input_name": "tiger",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e94\u540d#\u864e",
      "id": 79,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#1",
      "id": 80,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#2",
      "id": 81,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#3",
      "id": 82,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#4",
      "id": 83,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#5",
      "id": 84,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#6",
      "id": 85,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#7",
      "id": 86,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#8",
      "id": 87,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#9",
      "id": 88,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#10",
      "id": 89,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#\u5927",
      "id": 90,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#\u5c0f",
      "id": 91,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#\u5355",
      "id": 92,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "sixth",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516d\u540d#\u53cc",
      "id": 93,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#1",
      "id": 94,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#2",
      "id": 95,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#3",
      "id": 96,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#4",
      "id": 97,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#5",
      "id": 98,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#6",
      "id": 99,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#7",
      "id": 100,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#8",
      "id": 101,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#9",
      "id": 102,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#10",
      "id": 103,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#\u5927",
      "id": 104,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#\u5c0f",
      "id": 105,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#\u5355",
      "id": 106,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "seventh",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e03\u540d#\u53cc",
      "id": 107,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#1",
      "id": 108,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#2",
      "id": 109,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#3",
      "id": 110,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#4",
      "id": 111,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#5",
      "id": 112,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#6",
      "id": 113,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#7",
      "id": 114,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#8",
      "id": 115,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#9",
      "id": 116,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#10",
      "id": 117,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#\u5927",
      "id": 118,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#\u5c0f",
      "id": 119,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#\u5355",
      "id": 120,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "eighth",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u516b\u540d#\u53cc",
      "id": 121,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#1",
      "id": 122,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#2",
      "id": 123,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#3",
      "id": 124,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#4",
      "id": 125,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#5",
      "id": 126,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#6",
      "id": 127,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#7",
      "id": 128,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#8",
      "id": 129,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#9",
      "id": 130,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#10",
      "id": 131,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#\u5927",
      "id": 132,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#\u5c0f",
      "id": 133,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#\u5355",
      "id": 134,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "ninth",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e5d\u540d#\u53cc",
      "id": 135,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#1",
      "id": 136,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#2",
      "id": 137,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#3",
      "id": 138,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#4",
      "id": 139,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#5",
      "id": 140,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#6",
      "id": 141,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#7",
      "id": 142,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#8",
      "id": 143,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#9",
      "id": 144,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "10",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#10",
      "id": 145,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#\u5927",
      "id": 146,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#\u5c0f",
      "id": 147,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#\u5355",
      "id": 148,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "tenth",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u5341\u540d#\u53cc",
      "id": 149,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "3",
      "odd": "41.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#3",
      "id": 150,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "4",
      "odd": "41.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#4",
      "id": 151,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "5",
      "odd": "21.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#5",
      "id": 152,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "6",
      "odd": "21.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#6",
      "id": 153,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "7",
      "odd": "14.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#7",
      "id": 154,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "8",
      "odd": "14.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#8",
      "id": 155,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "9",
      "odd": "11.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#9",
      "id": 156,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "10",
      "odd": "11.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#10",
      "id": 157,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "11",
      "odd": "9.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#11",
      "id": 158,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "12",
      "odd": "11.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#12",
      "id": 159,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "13",
      "odd": "11.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#13",
      "id": 160,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "14",
      "odd": "14.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#14",
      "id": 161,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "15",
      "odd": "14.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#15",
      "id": 162,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "16",
      "odd": "21.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#16",
      "id": 163,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "17",
      "odd": "21.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#17",
      "id": 164,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "18",
      "odd": "41.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#18",
      "id": 165,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "19",
      "odd": "41.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#19",
      "id": 166,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "first_second_big",
      "odd": "2.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#\u51a0\u4e9a\u5927",
      "id": 167,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "first_second_small",
      "odd": "1.75",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#\u51a0\u4e9a\u5c0f",
      "id": 168,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "first_second_single",
      "odd": "1.75",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#\u51a0\u4e9a\u5355",
      "id": 169,
      "money": "0"
    }, {
      "fc_type": "bj_10",
      "gameplay": "first_second_sum",
      "input_name": "first_second_double",
      "odd": "2.00",
      "pankou": "A",
      "remark": "\u51a0\u4e9a\u519b\u548c#\u51a0\u4e9a\u53cc",
      "id": 170,
      "money": "0"
    }], "qishu": 651939, "closetime": {
      "kaipan": 1511242320, "fengpan": 1511242590, "kaijiang": 1511242620
    }
  }
  ,
  "ErrorCode": 1, "ErrorMsg": "\u83b7\u53d6\u6570\u636e\u6210\u529f"
}
export default data
