/**
 * Created by huygo on 2017/12/22.
 */
document.writeln("<div class=\'min\' style=\'display: none;\'>");
document.writeln("                            <dl>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'gpc window_img\'>");
document.writeln("                                    <span class=\'window_text\'>高频彩：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=bj_10.html?tab=1\'>北京赛车pk拾</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=ffc_o.html?tab=1\'>分分彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=lfc_o.html?tab=1\'>两分彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=jsfc.html?tab=1\'>极速飞车</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=els_o.html?tab=1\'>俄罗斯1.5分彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=mg_o.html?tab=1\'>美国45秒彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=xdl_10.html?tab=1\'>新德里PK拾</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=dj_o.html?tab=1\'>东京1.5分彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=xxl_o.html?tab=1\'>马尼拉45秒彩</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'klc window_img\'>");
document.writeln("                                    <span class=\'window_text\'>快乐彩：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=dm_klc.html?tab=1\'>丹麦快乐彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=jnd_bs.html?tab=1\'>加拿大卑斯</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=bj_kl8.html?tab=1\'>北京快乐8</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'ssc window_img\'>");
document.writeln("                                    <span class=\'window_text\'>时时彩：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=xj_ssc.html?tab=1\'>新疆时时彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=tj_ssc.html?tab=1\'>天津时时彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=cq_ssc.html?tab=1\'>重庆时时彩</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'sf window_img\'>");
document.writeln("                                    <span class=\'window_text\'>快乐十分：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=gd_ten.html?tab=1\'>广东快乐十分</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=cq_ten.html?tab=1\'>重庆快乐十分</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'k3 window_img\'>");
document.writeln("                                    <span class=\'window_text\'>快三：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=ah_k3.html?tab=1\'>安徽快3</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=gx_k3.html?tab=1\'>广西快3</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=js_k3.html?tab=1\'>江苏快3</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'11 window_img\'>");
document.writeln("                                    <span class=\'window_text\'>十一选五：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=jx_11.html?tab=1\'>江西11选5</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=sd_11.html?tab=1\'>山东11选5</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=gd_11.html?tab=1\'>广东11选5</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'xy window_img\'>");
document.writeln("                                    <span class=\'window_text\'>幸运彩：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=dm_28.html?tab=1\'>丹麦28</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=jnd_28.html?tab=1\'>加拿大28</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=pc_28.html?tab=1\'>PC蛋蛋</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=bj_28.html?tab=1\'>PK北京28</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                            <dl>");
document.writeln("                                <dt>");
document.writeln("                                    <img class=\'yb window_img\'>");
document.writeln("                                    <span class=\'window_text\'>一般彩：</span>");
document.writeln("                                </dt>");
document.writeln("                                <dd>");
document.writeln("                                    <ul>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=liuhecai.html?tab=1\'>六合彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=jsliuhecai.html?tab=1\'>极速六合彩</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=pl_3.html?tab=1\'>排列三</a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                            <a href=\'chart-lotteryId=fc_3d.html?tab=1\'>福彩3D</a>");
document.writeln("                                        </li>");
document.writeln("                                    </ul>");
document.writeln("                                </dd>");
document.writeln("                            </dl>");
document.writeln("                        </div>");
