const data = {
  "Data": {
    "odds": [{
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "3",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u548c\u503c#3",
      "mingxi": "",
      "id": 0,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "4",
      "odd": "44.00",
      "pankou": "A",
      "remark": "\u548c\u503c#4",
      "mingxi": "",
      "id": 1,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "5",
      "odd": "25.00",
      "pankou": "A",
      "remark": "\u548c\u503c#5",
      "mingxi": "",
      "id": 2,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "6",
      "odd": "15.00",
      "pankou": "A",
      "remark": "\u548c\u503c#6",
      "mingxi": "",
      "id": 3,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "7",
      "odd": "10.00",
      "pankou": "A",
      "remark": "\u548c\u503c#7",
      "mingxi": "",
      "id": 4,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "8",
      "odd": "7.20",
      "pankou": "A",
      "remark": "\u548c\u503c#8",
      "mingxi": "",
      "id": 5,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "9",
      "odd": "6.05",
      "pankou": "A",
      "remark": "\u548c\u503c#9",
      "mingxi": "",
      "id": 6,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "10",
      "odd": "5.60",
      "pankou": "A",
      "remark": "\u548c\u503c#10",
      "mingxi": "",
      "id": 7,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "11",
      "odd": "5.60",
      "pankou": "A",
      "remark": "\u548c\u503c#11",
      "mingxi": "",
      "id": 8,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "12",
      "odd": "6.05",
      "pankou": "A",
      "remark": "\u548c\u503c#12",
      "mingxi": "",
      "id": 9,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "13",
      "odd": "7.20",
      "pankou": "A",
      "remark": "\u548c\u503c#13",
      "mingxi": "",
      "id": 10,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "14",
      "odd": "10.00",
      "pankou": "A",
      "remark": "\u548c\u503c#14",
      "mingxi": "",
      "id": 11,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "15",
      "odd": "15.00",
      "pankou": "A",
      "remark": "\u548c\u503c#15",
      "mingxi": "",
      "id": 12,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "16",
      "odd": "25.00",
      "pankou": "A",
      "remark": "\u548c\u503c#16",
      "mingxi": "",
      "id": 13,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "17",
      "odd": "44.00",
      "pankou": "A",
      "remark": "\u548c\u503c#17",
      "mingxi": "",
      "id": 14,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "18",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u548c\u503c#18",
      "mingxi": "",
      "id": 15,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "big",
      "odd": "1.97",
      "pankou": "A",
      "remark": "\u548c\u503c#\u5927",
      "mingxi": "",
      "id": 16,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "small",
      "odd": "1.97",
      "pankou": "A",
      "remark": "\u548c\u503c#\u5c0f",
      "mingxi": "",
      "id": 17,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "single",
      "odd": "1.97",
      "pankou": "A",
      "remark": "\u548c\u503c#\u5355",
      "mingxi": "",
      "id": 18,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "sum",
      "input_name": "double",
      "odd": "1.97",
      "pankou": "A",
      "remark": "\u548c\u503c#\u53cc",
      "mingxi": "",
      "id": 19,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "gallbladder_ball",
      "input_name": "1",
      "odd": "2.05",
      "pankou": "A",
      "remark": "\u72ec\u80c6#1",
      "mingxi": "",
      "id": 20,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "gallbladder_ball",
      "input_name": "2",
      "odd": "2.05",
      "pankou": "A",
      "remark": "\u72ec\u80c6#2",
      "mingxi": "",
      "id": 21,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "gallbladder_ball",
      "input_name": "3",
      "odd": "2.05",
      "pankou": "A",
      "remark": "\u72ec\u80c6#3",
      "mingxi": "",
      "id": 22,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "gallbladder_ball",
      "input_name": "4",
      "odd": "2.05",
      "pankou": "A",
      "remark": "\u72ec\u80c6#4",
      "mingxi": "",
      "id": 23,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "gallbladder_ball",
      "input_name": "5",
      "odd": "2.05",
      "pankou": "A",
      "remark": "\u72ec\u80c6#5",
      "mingxi": "",
      "id": 24,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "gallbladder_ball",
      "input_name": "6",
      "odd": "2.05",
      "pankou": "A",
      "remark": "\u72ec\u80c6#6",
      "mingxi": "",
      "id": 25,
      "money": ""
    },
    {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "1,1,1",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u8c79\u5b50#1,1,1",
      "mingxi": "",
      "id": 26,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "2,2,2",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u8c79\u5b50#2,2,2",
      "mingxi": "",
      "id": 27,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "3,3,3",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u8c79\u5b50#3,3,3",
      "mingxi": "",
      "id": 28,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "4,4,4",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u8c79\u5b50#4,4,4",
      "mingxi": "",
      "id": 29,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "5,5,5",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u8c79\u5b50#5,5,5",
      "mingxi": "",
      "id": 30,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "6,6,6",
      "odd": "165.00",
      "pankou": "A",
      "remark": "\u8c79\u5b50#6,6,6",
      "mingxi": "",
      "id": 31,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "leopard",
      "input_name": "任意豹子",
      "odd": "27.50",
      "pankou": "A",
      "remark": "\u8c79\u5b50#\u4efb\u610f\u8c79\u5b50",
      "mingxi": "",
      "id": 32,
      "money": ""
    },
     {
      "fc_type": "js_k3",
      "gameplay": "pairs",
      "input_name": "1,1",
      "odd": "9.80",
      "pankou": "A",
      "remark": "\u5bf9\u5b50#1,1",
      "mingxi": "",
      "id": 33,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "pairs",
      "input_name": "2,2",
      "odd": "9.80",
      "pankou": "A",
      "remark": "\u5bf9\u5b50#2,2",
      "mingxi": "",
      "id": 34,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "pairs",
      "input_name": "3,3",
      "odd": "9.80",
      "pankou": "A",
      "remark": "\u5bf9\u5b50#3,3",
      "mingxi": "",
      "id": 35,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "pairs",
      "input_name": "4,4",
      "odd": "9.80",
      "pankou": "A",
      "remark": "\u5bf9\u5b50#4,4",
      "mingxi": "",
      "id": 36,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "pairs",
      "input_name": "5,5",
      "odd": "9.80",
      "pankou": "A",
      "remark": "\u5bf9\u5b50#5,5",
      "mingxi": "",
      "id": 37,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "pairs",
      "input_name": "6,6",
      "odd": "9.80",
      "pankou": "A",
      "remark": "\u5bf9\u5b50#6,6",
      "mingxi": "",
      "id": 38,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "1,3",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#1,3",
      "mingxi": "",
      "id": 39,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "1,4",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#1,4",
      "mingxi": "",
      "id": 40,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "1,5",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#1,5",
      "mingxi": "",
      "id": 41,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "1,6",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#1,6",
      "mingxi": "",
      "id": 42,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "2,3",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#2,3",
      "mingxi": "",
      "id": 43,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "2,4",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#2,4",
      "mingxi": "",
      "id": 44,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "2,5",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#2,5",
      "mingxi": "",
      "id": 45,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "2,6",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#2,6",
      "mingxi": "",
      "id": 46,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "3,4",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#3,4",
      "mingxi": "",
      "id": 47,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "3,5",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#3,5",
      "mingxi": "",
      "id": 48,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "3,6",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#3,6",
      "mingxi": "",
      "id": 49,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "4,5",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#4,5",
      "mingxi": "",
      "id": 50,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "4,6",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#4,6",
      "mingxi": "",
      "id": 51,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "5,6",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#5,6",
      "mingxi": "",
      "id": 52,
      "money": ""
    }, {
      "fc_type": "js_k3",
      "gameplay": "two_even",
      "input_name": "1,2",
      "odd": "4.80",
      "pankou": "A",
      "remark": "\u4e24\u8fde#1,2",
      "mingxi": "",
      "id": 53,
      "money": ""
    }, ],
    "qishu": "20171123036",
    "closetime": {
      "kaipan": 1511418000,
      "fengpan": 1511418450,
      "kaijiang": 1511418600
    }
  },
  "ErrorCode": 1,
  "ErrorMsg": "\u83b7\u53d6\u6570\u636e\u6210\u529f"
}
export default data;
