const data = {
      "Data": {
        "odds": [{
          "fc_type": "bj_kl8",
          "gameplay": "choose_one",
          "input_name": "",
          "odd": "3.00",
          "pankou": "A",
          "remark": "\u9009\u4e00",
          "mingxi": "one_in_one",
          "id": 0,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "choose_two",
          "input_name": "",
          "odd": "2\/2:10",
          "pankou": "A",
          "remark": "\u9009\u4e8c",
          "mingxi": "two_in_two",
          "id": 1,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "choose_three",
          "input_name": "",
          "odd": "3\/3:20,3\/2:3",
          "pankou": "A",
          "remark": "\u9009\u4e09",
          "mingxi": "three_in_two",
          "id": 3,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "choose_four",
          "input_name": "",
          "odd": "4\/4:50,4\/2:3,",
          "pankou": "A",
          "remark": "\u9009\u56db",
          "mingxi": "four_in_two",
          "id": 6,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "choose_five",
          "input_name": "",
          "odd": "5\/5:250,5\/4:20,5\/3:5",
          "pankou": "A",
          "remark": "\u9009\u4e94",
          "mingxi": "five_in_three",
          "id": 9,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "sum",
          "input_name": "total_sum_big",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u548c\u503c#\u603b\u548c\u5927",
          "mingxi": "",
          "id": 10,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "sum",
          "input_name": "total_sum_small",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u548c\u503c#\u603b\u548c\u5c0f",
          "mingxi": "",
          "id": 11,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "sum",
          "input_name": "total_sum_single",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u548c\u503c#\u603b\u548c\u5355",
          "mingxi": "",
          "id": 12,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "sum",
          "input_name": "total_sum_double",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u548c\u503c#\u603b\u548c\u53cc",
          "mingxi": "",
          "id": 13,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "sum",
          "input_name": "total_sum_810",
          "odd": "50.00",
          "pankou": "A",
          "remark": "\u548c\u503c#\u603b\u548c810",
          "mingxi": "",
          "id": 14,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "up_middle_down",
          "input_name": "up_disc",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u4e0a\u4e2d\u4e0b#\u4e0a\u76d8",
          "mingxi": "",
          "id": 15,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "up_middle_down",
          "input_name": "middle_disc",
          "odd": "2.80",
          "pankou": "A",
          "remark": "\u4e0a\u4e2d\u4e0b#\u4e2d\u76d8",
          "mingxi": "",
          "id": 16,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "up_middle_down",
          "input_name": "down_disc",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u4e0a\u4e2d\u4e0b#\u4e0b\u76d8",
          "mingxi": "",
          "id": 17,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "odd_and_even",
          "input_name": "odd_disc",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u5947\u5076#\u5947\u76d8",
          "mingxi": "",
          "id": 18,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "odd_and_even",
          "input_name": "sum_disc",
          "odd": "2.80",
          "pankou": "A",
          "remark": "\u5947\u5076#\u548c\u76d8",
          "mingxi": "",
          "id": 19,
          "money": ""
        }, {
          "fc_type": "bj_kl8",
          "gameplay": "odd_and_even",
          "input_name": "even_disc",
          "odd": "1.93",
          "pankou": "A",
          "remark": "\u5947\u5076#\u5076\u76d8",
          "mingxi": "",
          "id": 20,
          "money": ""
        }],
        "qishu": 857607,
        "closetime": {
          "kaipan": 1511346600,
          "fengpan": 1511346870,
          "kaijiang": 1511346900
        }
      },
      "ErrorCode": 1,
      "ErrorMsg": "\u83b7\u53d6\u6570\u636e\u6210\u529f"
    }
export default data;
