package langs

var CNLangsAdmin = `{
  "Immediate audit query":"即时稽核查询",
  "videoNote":"视讯管理",
  "videoWiteList":"视讯白名单",
  "bankMangement":"银行卡列表",
  "statistical":"统计管理",
  "redPacket": "红包补数据",
  "Date interva": "时区",
  "templateManagement": "模板管理",
  "lineStatus": "登录状态",
  "PROJECTS": "项目",
  "Msgs": "封邮件",
  "Notify": "通知",
  "Tasks": "任务",
  "Recent projects": "最近项目",
  "Find reports and more": "查找报告和更多",
  "john.doe": "john.doe",
  "Dashboard": "仪表板",
  "Angular Stuff": "角的东西",
  "UI Bootstrap": "UI引导",
  "Get Locale JSON": "获取地点JSON",
  "Inbox": "收件箱",
  "Graphs": "图",
  "Flot Chart": "海军报图",
  "Morris Charts": "莫里斯图表",
  "Inline Charts": "内嵌图表",
  "Dygraphs": "Dygraphs",
  "Tables": "表",
  "Normal Tables": "普通表",
  "Data Tables": "数据表",
  "Forms": "形式",
  "Smart Form Elements": "智能表单元素",
  "Smart Form Layouts": "智能表布局",
  "Smart Form Validation": "智能表单验证",
  "Bootstrap Form Elements": "引导表单元素",
  "Bootstrap Form Validation": "引导表单验证",
  "Outlook": "前景",
  "Cool Features": "很酷的功能",
  "App Views": "应用程序浏览",
  "Form Plugins": "表格插件",
  "Wizards": "奇才",
  "Bootstrap Editors": "引导编辑",
  "Dropzone": "悬浮窗",
  "UI Elements": "UI元素",
  "General Elements": "一般信息",
  "E-Commerce": "电子商务",
  "Buttons": "按钮",
  "Icons": "图标",
  "Font Awesome": "字体真棒",
  "Glyph Icons": "字形图标",
  "Grid": "格",
  "Tree View": "树视图",
  "Nestable Lists": "嵌套列表",
  "JQuery UI": "JQuery用户界面",
  "Typography": "活版印刷",
  "Six Level Menu": "六级菜单",
  "Item #2": "Item #2",
  "Sub #2.1": "Sub #2.1",
  "Item #2.1.1": "Item #2.1.1",
  "Expand": "扩大",
  "File": "文件",
  "Delete": "删除",
  "Item #3": "项目＃ 3",
  "3rd Level": "第三层",
  "Calendar": "日历",
  "Widgets": "小工具",
  "Gallery": "画廊",
  "GMap Skins": "GMAP皮肤",
  "Miscellaneous": "杂",
  "Other Pages": "其他页",
  "Forum Layout": "版块布局",
  "Profile": "简介",
  "Timeline": "时间线",
  "Pricing Tables": "价格表",
  "Invoice": "发票",
  "Login": "登录",
  "Register": "寄存器",
  "Locked Screen": "锁定屏幕",
  "Error 404": "错误404",
  "Error 500": "错误500",
  "Blank Page": "空白页",
  "Email Template": "电子邮件模板",
  "Search Page": "検索ページ",
  "CK Editor": "CK编辑器",
  "SmartAdmin Intel": "SmartAdmin英特尔",
  "Different Versions": "不同版本",
  "Documentation": "文件",
  "Bug Tracker": "Bug跟踪",
  "Mail": "邮件",
  "Maps": "地图",
  "My Profile": "我的简历",
  "Page Header": "页眉",
  "Subtitle": "字幕",
  "Permission Grouping": "权限分组",
  "Admin Account": "管理员账号",
  "Admin Log": "管理日志",
  "Dealer Management": "经销商管理",
  "Commodity": "商品管理",
  "Sort Management": "分类管理",
  "Release goods": "发布商品",
  "Site List": "站点列表",
  "Create Site": "创建站点",
  "Order Management": "订单管理",
  "Settlement": "结算管理",
  "Pending application": "待结算申请",
  "Settlement record": "已结算记录",
  "Payment Management": "支付管理",
  "Customer Management": "会员管理",
  "Customer Info": "会员资料",
  "Search": "搜索",
  "AddMore": "添加",
  "GroupName": "分组名称",
  "Administrator Management": "管理员管理",
  "Administrator Number": "管理员管理",
  "Status": "状态",
  "Remarks": "备注",
  "PreviousPage": "上一页",
  "NextPage": "下一页",
  "Edit": "编辑",
  "Order List": "订单列表",
  "Classification of goods": "商品分类",
  "Payment channel": "支付渠道",
  "State": "状态",
  "Please enter the name of the commodity": "请输入商品名称",
  "Commodity name": "商品名称",
  "Unit price / quantity": "单价/数量",
  "Owned dealer": "所属经销商",
  "Order status": "订单状态",
  "General Commission": "总佣金",
  "Home": "首页",
  "Settlement management": "结算管理",
  "Settlement request": "待结算申请",
  "List of settlement requests": "待结算申请列表",
  "Start time of order creation": "订单创建开始时间",
  "Order creation end time": "订单创建结束时间",
  "Dealer name search": "经销商名称搜索",
  "Order ID": "订单ID",
  "Dealer name": "经销商名称",
  "Application time": "提出申请时间",
  "Balance of settlement": "可结算余额",
  "Settlement amount": "结算金额",
  "Administration": "管理",
  "Payment interface management": "支付接口管理",
  "Payment interface list": "支付接口列表",
  "Add interface": "添加接口",
  "Service provider logo": "服务商logo",
  "Interface name": "接口名称",
  "ID": "ID",
  "Flow amount": "流水金额",
  "Site": "站点",
  "Customer nickname": "会员昵称",
  "List of customer management": "会员管理列表",
  "Customer source": "客户来源",
  "Customer ID": "会员ID",
  "Subordinate site": "所属站点",
  "A turnover": "交易额",
  "integral": "积分",
  "operation": "操作",
  "Administrator account": "管理员账号",
  "Select group name": "选择分组名称",
  "Administrator account search": "请输入搜索关键字",
  "Accounts": "账号",
  "Creation Time": "创建时间",
  "Dealer ID": "经销商ID",
  "Total goods": "商品总数",
  "Total customer": "会员总数",
  "Total order": "订单总数",
  "Total transaction": "交易总额",
  "Total distribution": "分销商总数",
  "Distributor order totals": "分销商订单总数",
  "Distributor transaction volume": "分销交易总额",
  "Total settlement": "已结算总额",
  "Registration time": "注册时间",
  "Settlement amount to be processed": "待处理结算(数量)",
  "Site management": "站点管理",
  "Choose dealers": "选择经销商",
  "site": "站点",
  "ChildAccount": "子账号",
  "ChildAccount Power": "子账号权限",
  "MemberManagement": "会员管理",
  "FundManagement": "资金管理",
  "MarginManagement": "保证金管理",
  "ReCommisManagement": "返佣管理",
  "RebateManagement": "返点管理",
  "Announcement": "公告管理",
  "SiteChoice": "站点选择",
  "UserName": "用户名",
  "DividedManagement": "分成分组管理",
  "DealerQuantity": "经销商数量",
  "DivideInto": "分成比例",
  "CreatePacket": "创建分组",
  "SortType": "排序类型",
  "IsItEnabled": "是否启用",
  "DealerCommission": "经销商返佣比",
  "DistributorRegistration": "分销商注册设定",
  "Dealer grouping": "经销商权限分组",
  "AdministratorGrouping": "管理员数量",
  "addDelaer": "添加经销商",
  "DistributorName": "分销商名称",
  "OrderDetails": "订单详情",
  "Check all": "全选",
  "Batch pass": "批量通过",
  "Level": "级别",
  "Name": "名称",
  "Balance": "余额",
  "Auditor": "审核人",
  "Reasons for rejection": "驳回原因",
  "Member source": "会员来源",
  "distributor": "分销商",
  "Online search": "在线搜索",
  "Member account": "会员账号",
  "Distributors": "所属分销商",
  "System balance": "系统余额",
  "Online": "是否在线",
  "Member registration settings": "会员注册设定",
  "members registered": "是否用户会员注册",
  "Tourist registration": "游客注册",
  "Registration requires mailbox": "注册需邮箱",
  "Are mailbox repeats allowed": "是否允许邮箱重复",
  "Registration requires QQ": "注册需要QQ",
  "Are you allowed to repeat QQ": "是否允许QQ重复",
  "Registration requires phone": "注册需要手机号",
  "Are you allowed to repeat phone": "是否允许手机号重复",
  "Registration requires birth date": "注册需要出生日期",
  "Open authentication code": "开启验证码",
  "Done": "完成",
  "Member order list": "会员订单列表",
  "Commodity type": "商品类型",
  "Settlement method": "结算方式",
  "Order number": "订单号",
  "Order time": "订单时间",
  "Transaction amount": "交易金额",
  "Purchase amount": "购买优惠金额",
  "Add packet": "添加分组",
  "Packet information": "分组信息",
  "Privilege management": "权限管理",
  "Functional module": "功能模块",
  "Function selection": "功能选择",
  "Module enabled": "是否启用模块",
  "Create success": "创建成功",
  "Create packet completion": "创建分组完成，可在管理员管理模块添加管理员到新创建的分组；在权限管理中可对分组进行权限管理。",
  "See": "查看",
  "Return list": "返回列表",
  "Previous step": "上一步",
  "Next step": "下一步",
  "Create schedule": "创建进度",
  "Add Account": "添加帐号",
  "accounts": "帐号",
  "Password": "密码",
  "Permission grouping": "权限分组",
  "Status enabled disabled": "状态启用禁用",
  "Enables": "启用",
  "Disable": "停用",
  "Confirm": "确认",
  "Cancel": "取消",
  "Journal": "日志",
  "Time": "时间",
  "Operation record": "操作记录",
  "Edit account": "编辑帐号",
  "Submit successfully": "提交成功",
  "View grouping": "查看分组",
  "Power": "权限",
  "Total administrator": "管理员总数",
  "Member list": "成员列表",
  "Operating time": "操作时间",
  "Grounping": "分组",
  "Permission view": "权限查看",
  "Basic information": "基础信息",
  "Confirm password": "确认密码",
  "Please enter your password again": "请再次输入密码",
  "Divide into groups": "分成分组",
  "Modify dealer": "修改经销商",
  "Confirm submission": "确定提交",
  "Modified grouping": "修改分成分组",
  "Enable proxy registration": "是否启用代理注册",
  "Primary dealer": "一级经销商",
  "Two dealer": "二级经销商",
  "Please enter": "请输入",
  "Distributor quantity": "分销商数量",
  "Distributor split ratio setting": "分销商分成比设定",
  "My ratio": "我的占比",
  "Subordinate ratio": "下级占比",
  "Packet creation": "分成分组创建",
  "Modify": "修改",
  "Please enter the name of the applicant": "请输入申请人名称",
  "Applicant ID": "申请人ID",
  "Applicant name": "申请人名称",
  "Subordinate": "所属上级",
  "CAAC Certificate No": "证件号",
  "Mailbox": "邮箱",
  "QQ": "QQ",
  "Cell-phone number": "手机号",
  "Management": "管理",
  "Child account list": "子账号列表",
  "Unit price": "单价售价",
  "Number of shelves": "上架次数",
  "Commission amount": "返佣金额",
  "Inventory quantity": "库存数量",
  "Batch shelves": "批量上架",
  "Batch Operation": "批量操作",
  "Details": "详情URL",
  "Are goods allowed on shelves": "是否允许商品上架",
  "Release": "发布",
  "(unit: yuan)": "（单位：元）",
  "Chinese: apples": "中文：苹果",
  "(unit: Unit)": "（单位：个）",
  "Class A": "一级",
  "Second level": "二级",
  "Three": "三级",
  "Commodity details page": "商品详情页面",
  "View details of the goods": "查看商品详情",
  "View commodity information": "查看商品信息",
  "Commodity attribute": "商品属性",
  "Publication quantity": "发布数量",
  "View categories": "查看分类",
  "Classified ID": "分类ID",
  "Category name": "分类名称",
  "Classification description": "分类描述",
  "Add categories": "添加分类",
  "Modify goods": "修改商品",
  "Site name": "站点名称",
  "Site information": "站点信息",
  "Tip": "提示",
  "Select site status": "请选择站点状态",
  "Select the dealer or manually enter the dealer name": "请选择经销商或手动输入经销商名称",
  "PC domain name": "PC域名",
  "Please enter the PC domain name": "请输入PC域名",
  "WAP domain name": "WAP域名",
  "Please enter the WAP domain name": "请输入WAP域名",
  "SSI certificate": "SSI证书",
  "Select file": "选择文件",
  "Click Add domain name and certificate customer service information": "点击添加域名及证书客服信息",
  "WeChat": "微信",
  "Telephone": "电话",
  "Email": "电邮",
  "Customer service information": "客服信息",
  "Modify site information": "修改站点信息",
  "EditAccount": "编辑账号",
  "EditGroup": "编辑分组",
  "LookPower": "查看权限分组",
  "MarginApplication": "保证金申请",
  "Order information": "订单信息",
  "Commodity information": "商品信息",
  "Single product discount": "单品优惠",
  "Quantity purchased": "购买数量",
  "Buy discount": "购买优惠",
  "Purchase amount1": "购买金额",
  "Operation type": "操作类型",
  "Deposit amount": "存款金额",
  "Deposit preferences": "存款优惠",
  "Access money": "存取款",
  "Sort": "排序",
  "Deposit / withdrawal amount": "存/取款金额",
  "Member name": "会员名称",
  "Commission list": "返佣列表",
  "Commission setting": "返佣设定",
  "Parent account": "父级账号",
  "Recommended number": "推荐人数",
  "Rebate list": "返点列表",
  "Margin application": "保证金申请",
  "Please enter a single number": "请输入单号",
  "New application": "新建申请",
  "Apply for an account": "申请账号",
  "Application amount": "申请金额",
  "Date of application": "申请日期",
  "Remittance mode": "汇款方式",
  "Report details": "报表详情",
  "Export EXCEL": "导出EXCEL",
  "User information": "用户信息",
  "Recharge warning": "充值预警",
  "Recharge application": "充值申请",
  "Recharge alert settings": "充值预警设定",
  "Debit note number": "扣款单号",
  "Deductible amount": "扣除金额",
  "Date of deduction": "扣款日期",
  "Associated single number": "关联单号",
  "Third party payment": "第三方支付",
  "Bank card transfer": "银行卡转账",
  "Bank remittance": "银行汇款",
  "Remittance form": "汇款表单",
  "Platform": "平台管理",
  "Girokonto": "转账账号",
  "Collection account": "收款账号",
  "Transfer amount": "转账金额",
  "Transfer time": "转账时间",
  "Bank name": "银行名称",
  "Transfer card number": "转账卡号",
  "Collection card number": "收款卡号",
  "Running odd numbers": "流水单号",
  "Rebate amount": "返点总额",
  "Set point": "返点设定",
  "Check rebate": "查看返点",
  "Report form": "报表",
  "End time": "结束时间",
  "Today": "今日",
  "Yesterday": "昨日",
  "Last week": "上周",
  "This period": "本期",
  "Number and period in 2016": "2016年月幅期数",
  "Number and period in 2017": "2017年月幅期数",
  "Report type": "报表类型",
  "New announcement": "新建公告",
  "Title": "标题",
  "Content": "内容",
  "Release time": "发布时间",
  "Publish account": "发布账号",
  "Type": "类型",
  "Dealer account": "经销商账号",
  "Announcement type": "公告类型",
  "Please select": "请选择",
  "Announcement heading": "公告标题",
  "Announcement content": "公告内容",
  "Subordinate group": "所属分组",
  "Recording time": "记录时间",
  "IP address": "IP地址",
  "Operation behavior": "操作行为",
  "Administrator operation": "管理员操作",
  "Grade": "等级",
  "SettlementRequest": "保证金申请",
  "DistributorBalance": "分销商余额查看",
  "Account management": "账号管理",
  "Distributor list": "分销商列表",
  "Distributor Application List": "分销商申请列表",
  "Distributor application setting": "分销商申请设定",
  "Transaction management": "交易管理",
  "Goods shelves (dealers)": "商品上架（经销商）",
  "List of goods on shelves": "上架商品列表",
  "Rebate settings": "返利设置",
  "SystemSettings": "系统设置",
  "Member registration management": "会员注册管理",
  "Member grouping management": "会员分组管理",
  "Distributor balance view": "分销商余额查看",
  "ReportForm": "报表管理",
  "A_1": "会员管理",
  "A_1_1": "正式账号",
  "A_1_2": "带玩账号",
  "A_1_3": "添加带玩",
  "A_2": "股东管理",
  "A_3": "总代理管理",
  "A_4": "代理管理",
  "A_5": "子账号",
  "A_6": "会员注册设定",
  "A_7": "代理申请管理",
  "A_8": "体系查询",
  "A_9": "层级管理",
  "A_10": "开户人管理",
  "Add Heriy": "添加层级",
  "Modify Heriy": "添加层级",
  "Bank": "出款银行",
  "Modify Agent Info": "修改代理资料",
  "Agent Domain": "代理域名",
  "DepositsWithdrawals": "人工存款",
  "HistoryQuery": "出入账目记录",
  "QuotaConversion": "额度转换",
  "MarginReplacement": "额度转换记录",
  "entryAndExit": "出入账目汇总",
  "CashManagement": "出款管理",
  "MoneyManagement": "入款管理",
  "companyInChina": "公司入款",
  "ChinaOnline": "线上入款",
  "Immediate": "即时稽核查询",
  "auditLog": "稽核日志",
  "PaymentSetting": "支付设定",
  "BankElimination": "出款银行剔除",
  "DepositBankSet": "入款银行设定",
  "IncomeExcludingBank": "入款银行剔除",
  "bankElimination": "第三方银行剔除",
  "OnlinePaymentSetup": "线上支付设定",
  "PaymentParameterSetting": "支付参数设定",
  "AutomaticCashSetting": "自动出款设定",
  "CashSystem": "现金流水",
  "MemberAnalysis": "会员分析",
  "Analysis": "出入款分析",
  "MemberInquiries": "会员查询",
  "PurchaseAnalysis": "购买分析",
  "PreferentialAnalysis": "退水分析",
  "ValidMembershipList": "有效会员列表",
  "CommissionStatistics": "退佣统计",
  "AgentRetirementSetting": "代理退佣设定",
  "PeriodManagement": "期数管理",
  "FeeSetting": "手续费设定",
  "CommissionInquiry": "退佣查询",
  "MemberBalance": "会员余额统计",
  "PreferentialCalculation": "优惠计算",
  "SetPreferential": "返点优惠设定",
  "PreferentialInquiry": "优惠查询",
  "PreferentialStatistics": "优惠统计",
  "SelfDefectionQuery": "自助反水查询",
  "MembershipReturns": "会员返佣",
  "CommissionSetting": "返佣查询",
  "RebateSetting": "返佣优惠设定",
  "MemberPromotionInquiries": "会员推广查询",
  "MemberPromotionSettings": "会员推广设定",
  "QuotaStatistics": "额度统计",
  "RechargeRecord": "充值记录",
  "DropList": "掉单列表",
  "QuotaRecharge": "额度充值",
  "QuotaRecord": "额度记录",
  "AnnouncementInformation": "公告信息",
  "SystemAnnouncement": "系统公告",
  "MemberMessage": "会员消息",
  "ReleaseNewMessages": "发布新消息",
  "RegistrationCouponTemplates": "注册优惠消息模板",
  "LatestNews": "最新消息",
  "LogManagement": "日志管理",
  "MemberLogin": "会员登录",
  "AdministratorLogin": "管理员登录",
  "OperationLog": "操作日志",
  "AutomaticAudit": "自动稽核",
  "WebsiteManagement": "网站资讯管理",
  "SiteDataEditor": "站点资料编辑",
  "GraphicEditor": "图文编辑",
  "CopyEditor": "文案编辑",
  "CaseEditor": "案件编辑",
  "ThePendingCase": "待审案件",
  "InThePendingCase": "待审中案件",
  "ThroughCase": "通过案件",
  "QuashCase": "撤销案件",
  "Membership details": "会员详情",
  "describe": "描述",
  "Join condition": "加入条件",
  "membership": "会员人数",
  "Self service return water": "自助返水",
  "Membership time": "会员加入时间",
  "Deposit times": "存款次数",
  "Total deposits": "存款总额",
  "Member hierarchy": "会员分层",
  "Layered": "分层",
  "regression": "回归",
  "Payment settings": "支付设置",
  "Verify that the user is moved to non - hierarchical ?": "确认要将该用户移到未分层?",
  "Hierarchical query": "层级查询",
  "Shareholder": "所属股东",
  "General agent": "所属总代理",
  "agent": "所属代理商",
  "Fuzzy query": "模糊查询",
  "Serial number": "序号",
  "Member": "会员",
  "Registration settings": "注册设定",
  "Nickname Chinese": "中文昵称",
  "Promotion URL": "推广网址",
  "function": "功能",
  "New account": "新增账号",
  "Detailed content": "详情内容",
  "New proxy account": "新增代理账号",
  "Proxy name": "代理名称",
  "Proxy information": "代理资料",
  "Proxy account": "代理账号",
  "Real name": "真实姓名",
  "English name": "英语名称",
  "ID number": "身份证号码",
  "Withdrawal bank": "取款银行",
  "Bank account": "银行账号",
  "Province": "省份",
  "Counties and cities": "县市",
  "ATM password": "取款密码",
  "Other promotion methods": "其他推广方式",
  "Enable Member registration": "是否启用会员注册",
  "No": "否",
  "The date of birth is the indication of whether or not it is hidden": "出生日期【是表示显示，否表示隐藏】",
  "The introducer is said to show, not to hide": "介绍人【是表示显示，否表示隐藏】",
  "The promoters name is show no means hide": "推广人姓名【是表示显示，否表示隐藏】",
  "Name repetition means permission to repeat": "姓名重复【是表示允许重复】",
  "Password authentication settings": "口令验证设置",
  "On-line": "在线",
  "whole": "全部",
  "Line": "线下",
  "Last logon time": "最后登录时间",
  "Finally login to IP": "最后登录IP",
  "New date": "新增日期",
  "Landing error times": "登录错误次数",
  "current state": "当前状态",
  "suspend": "暂停",
  "Operation password": "操作密码",
  "Do you need a password": "是否需要密码",
  "Do you want to enable dynamic password settings": "是否启用动态口令设置",
  "secret key": "密钥",
  "Promote domain names": "代理推广域名",
  "Popularizing ID": "推广ID",
  "Login account": "登录账号",
  "Membership": "会员数",
  "Sports accounted for": "体育占成",
  "Video accounting": "视讯占成",
  "status": "状况",
  "Set up": "设定",
  "datum": "资料",
  "Discount": "优惠活动",
  "Domain extension": "推广域名",
  "General agent name": "总代理名称",
  "General agent account number": "总代理账号",
  "Lottery accounts for": "彩票占成",
  "Modify the general agent account": "修改总代理账号",
  "Member registration privilege setting": "旗下会员注册优惠设定",
  "Apply for membership registration privilege": "申请会员注册优惠",
  "Discount code": "优惠打码",
  "times": "倍",
  "Limit IP": "限制IP",
  "Clear lower level settings": "是否清除下级设定",
  "Shareholder account": "股东账号",
  "Hidden": "是否隐藏",
  "source": "来源",
  "Registration date": "注册日期",
  "sort": "排序",
  "System quota": "系统额度",
  "Video balance": "视讯额度",
  "Kick line": "踢线",
  "Bet": "下注",
  "cash": "现金",
  "To update": "更新",
  "Modify member account": "修改会员账号",
  "Can I change the password": "是否可修改密码",
  "Do you need a mailbox for registration": "注册是否需要邮箱",
  "Does registration require WeChat": "注册是否需要微信",
  "Does registration require documentation": "注册是否需要证件",
  "Do you need a telephone for registration": "注册是否需要电话",
  "Does registration require birthdays": "注册是否需要生日",
  "enable Member registration": "是否启用会员注册",
  "Do you need real names": "是否需要真实姓名",
  "Whether to display the introducer": "是否显示介绍人",
  "Do you need to fill in the bank card number": "注册是否需要填写银行卡号",
  "Can the phone be repeated": "电话是否可以重复",
  "Can the mailbox be repeated": "邮箱是否可以重复",
  "Can QQ repeat": "QQ是否可以重复",
  "Can WeChat repeat it": "微信是否可以重复",
  "Do you want to open the authentication code": "是否开启验证码",
  "Membership application amount": "会员申请优惠金额",
  "Code": "打码",
  "Do you want to limit IP": "是否限制IP",
  "Does registration require QQ": "注册是否需要QQ",
  "Need": "需要",
  "Unwanted": "不需要",
  "Sure": "可以",
  "May not": "不可以",
  "application time": "申请时间",
  "Do you want to enable proxy registration settings": "是否启用代理注册设定",
  "Do you have a Chinese nickname": "是否中文昵称",
  "Do you have a English nickname": "是否英文昵称",
  "Do you need ID number": "是否需要证件号",
  "Do you need a mailbox": "是否需要邮箱",
  "Do you need QQ": "是否需要QQ",
  "Do you need phone number": "是否需要电话号",
  "Do you need to promote the URL": "是否需要推广网址",
  "Do you need any other methods": "是否需要其他方法",
  "Chinese nickname is required": "中文昵称是否必填",
  "English nickname is required": "英文昵称是否必填",
  "Whether the mailbox is required": "邮箱是否必填",
  "Documents are required": "证件是否必填",
  "QQ is required": "QQ是否必填",
  "Mobile phone number is required": "手机号是否必填",
  "The URL is required for promotion": "推广网址是否必填",
  "The other way is required": "其他方式是否必填",
  "Proxy registration settings": "代理注册设定",
  "ExitManagement": "出入款管理",
  "ArtificialWithdrawal": "人工取款",
  "AuditManagement": "稽核管理",
  "PlatformManagement": "管理员",
  "CommodityManagement": "商品管理",
  "PlatformAccount": "平台管理",
  "AccountManagement": "开户人管理",
  "RoleManagement": "角色管理",
  "MenuManagement": "菜单管理",
  "FunctionManagement": "权限管理",
  "PackageManagement": "套餐管理",
  "WebsiteInformation": "网站信息",
  "videoManagement": "视讯管理",
  "electronicManagement": "电子管理",
  "sportManagement": "体育管理",
  "lotteryManagrment": "彩票管理",
  "modularManagement": "模块管理",
  "PreferencesSettings": "自助申请优惠设置",
  "cacheManagement": "缓存管理",
  "LogoManagement": "LOGO管理",
  "FloatImg": "浮动图片",
  "SwiperImg": "轮播图片",
  "Notice": "公告弹框",
  "Advertisement": "广告管理",
  "GamePic": "首页游戏图",
  "Upload": "附件上传",
  "Attachment": "附件管理",
  "HomeCopy": "首页文案",
  "DepositCopy": "存款文案",
  "RegisterCopy": "注册文案",
  "WapDiscount": "WAP优惠活动",
  "LineDetection": "线路检测",
  "NewApplication": "银行卡设定",
  "screening": "筛选",
  "Platformaccount": "平台管理列表",
  "Functionmanagement": "功能管理",
  "Typemanagement": "类型管理",
  "configuration": "配置管理",
  "Layout Options": "布局选项",
  "Fixed Header": "固定头",
  "Fixed Navigation": "固定导航",
  "Fixed Ribbon": "固定带",
  "Fixed Footer": "固定页脚",
  "Inside": "容器",
  "container": "内",
  "RTL": "RTL",
  "Menu on top": "菜单上",
  "For Colorblind": "对于色盲",
  "experimental": "实验",
  "Clear Local storage": "清除本地存储",
  "Factory Reset": "恢复出厂设置",
  "Smart Admin Skins": "智能管理皮肤",
  "Smart Default": "智能默认",
  "Dark Elegance": "黑暗的优雅",
  "Ultra Light": "超轻",
  "Google Skin": "谷歌的皮肤",
  "Pixel Smash": "像素粉碎",
  "Glass": "玻璃",
  "Material Design beta": "材料设计测试",
  "success": "操作成功",
  "confirmationOperation": "是否确认此操作",
  "confirmStorage": "确定存储",
  "confirmEnable": "确定启用",
  "confirmDisable": "确定禁用",
  "birthdays": "出生日期",
  "rmdRequired": "RMB表示人民币，必选",
  "hierarchyName": "层级名称",
  "fixedNumber": "固定编号（最多4位）",
  "requiredSpecialCharacters": "必填，请勿使用特殊字符",
  "default0,isUnrestricted": "默认0为整数，0表示无限制",
  "Return": "返回",
  "addDomain": "添加域名",
  "modifyDomain": "修改域名",
  "addPromoteDomain": "添加代理推广域名",
  "englishName": "英文名称",
  "agentModification": "代理管理资料修改",
  "area": "区",
  "cardNum": "银行卡号",
  "accountLength": "数字字母（a-z）长度（4-12位）",
  "digitalLetter": "账号长度5-12位，只能字母和数字组合",
  "modifyUserBank": "修改会员银行",
  "bankBranch": "支行名称",
  "card": "卡号",
  "passwordDigitalLetter": "密码长度6-12位，只能字母和数字组合",
  "agentDigitalLetter": "总代理长度6-12位，只能字母和数字组合",
  "modifyChildren": "修改子账号",
  "maximumOnline": "在线存提款最大金额",
  "maximumArtificial": "人工存提款最大金额",
  "bindingLoginIP": "绑定登录IP",
  "passwordkey": "口令密钥",
  "paymentPlatform": "支付平台设定",
  "fixedNumberComposed": "固定编号由4位字母加数字组成，首字母位大写",
  "hierarchyModify": "修改层级",
  "tryGift": "试玩赠送额度",
  "trialRegistration": "试玩注册是否开启",
  "wapRegistration": "wap注册是否单页面",
  "modifyShareholder": "修改股东账号",
  "noSale": "为0时加入会员不赠送优惠",
  "bulkDeposit": "批量存款",
  "prepareMoney": "预备出款",
  "confirMation": "确认出款",
  "refuse": "拒绝",
  "reason": "原因",
  "confirmReceipt": "确认入款",
  "monitor": "监控",
  "rebateKeep": "退佣存档",
  "retreats": "退佣冲销",
  "addPeriods": "新增期数",
  "modifyPeriods": "修改期数",
  "layeredDetails": "分层详情",
  "depositRecord": "存款记录",
  "selfSetting": "公司自定设置",
  "rmbSet": "币别设定",
  "newSetting": "新增设定",
  "modifySetting": "修改设定",
  "detailed": "明细",
  "returnDetail": "返水明细",
  "modifyAnnouncement": "修改公告",
  "sendAudit": "发送审核",
  "choose": "选择",
  "modifyContent": "编辑内容",
  "templateChoose": "模板选择",
  "keep": "储存案件",
  "update": "上传",
  "saleContent": "优惠内容",
  "themeConfigure": "电子内页主题配置",
  "modifySort": "编辑顺序",
  "invalid": "置为无效",
  "siteColumn": "站点栏目",
  "maintenance": "维护管理",
  "informationAudit": "资讯审核",
  "sitePwdSettings": "站点口令设置",
  "linkManagement": "下载链接管理",
  "wapJS": "更新wap端js版本号",
  "ipOperation": "ip开关操作",
  "financialStatements": "财务报表",
  "cashStatement": "现金报表",
  "dataCenter": "数据中心",
  "incomeStatistics": "入款统计",
  "reportAssistant": "报表辅助查询",
  "dunningQuery": "催款查询",
  "reportStatistics": "报表统计",
  "reportQuery": "报表查询",
  "customerManagement": "客户后台管理",
  "userManagement": "用户管理",
  "subaccount": "子账号管理",
  "keyManagement": "公钥密匙管理",
  "applicationInquiry": "自助优惠申请查询",
  "boardManagement": "公告弹框管理",
  "ExceptionMember": "异常会员查询",
  "videoAccount": "视讯账号管理",
  "copywritingTemplate": "文案模板管理",
  "registerTemplate": "注册模板管理",
  "videoTemplate": "视讯模板管理",
  "siteStatistics": "站点统计数据",
  "billQuery": "账单查询",
  "role": "角色",
  "currentState": "当前状态",
  "search": "搜索",
  "add": "添加",
  "disable": "禁用",
  "Enable": "启用",
  "modify": "修改",
  "ConfirmPassword": "确认密码",
  "AccountStatus": "账号状态",
  "goUpAndDown": "升降序",
  "NewAccount": "新增开户账号",
  "AccountName": "开户名称",
  "AccountOpeningAccount": "开户账号",
  "PointNumber": "站点数",
  "shareholdersNumber": "股东数",
  "agentNumber": "总代理数",
  "dealersNumber": "经销商数",
  "membersNumber": "会员数",
  "NewDate": "新增日期",
  "RoleName": "角色名称",
  "addRole": "新增角色",
  "roleId": "角色ID",
  "CreationTime": "创建时间",
  "PlatformMenuManagement": "平台菜单管理",
  "ProxyMenuManagement": "代理菜单管理",
  "MenuName": "菜单名称",
  "Front-endRouting": "前端路由",
  "AddLowerLevel": "添加下级",
  "addMenu": "新增菜单",
  "CommodityType": "商品类型",
  "CommodityState": "商品状态",
  "searchCriteria": "搜索条件",
  "TypeManagement": "类型管理",
  "CommodityID": "商品ID",
  "CommodityName": "商品名称",
  "NewtType": "新建类型",
  "TypeNumber": "类型编号",
  "TypeName": "类型名称",
  "QuantityOfGoods": "商品数量",
  "NameOfRTheModule": "所属模块名称",
  "FunctionalName": "功能名称",
  "RequestMethod": "请求方式",
  "PlatformFunctionManagement": "平台功能管理",
  "AgentFunctionManagement": "代理功能管理",
  "NewFunction": "新增功能",
  "terrace": "所属平台",
  "ModuleName": "模块名称",
  "Route": "路由",
  "functionalStatus": "功能状态",
  "NewSetMeal": "新增套餐",
  "PackageID": "套餐ID",
  "SetName": "套餐名称",
  "AddTime": "添加时间",
  "SetMealState": "套餐状态",
  "ToConfigure": "配置",
  "account": "账户",
  "OperationIP": "操作IP",
  "OperationPath": "操作路径",
  "DateQuery": "日期查询",
  "Administrators": "管理员",
  "OperationContent": "操作内容",
  "OperatorIP": "操作人IP",
  "logInformation": "日志信息",
  "OperatingTime": "操作时间",
  "Operator": "操作者",
  "OperationTime": "操作时间",
  "AddTheaAddress": "添加地址",
  "number": "编号",
  "VideoCategory": "视讯类别",
  "IOSLink": "iOS链接",
  "AndroidLink": "安卓链接",
  "GenerateWEPVersion": "生成WEP版本号",
  "GeneratePCVersion": "生成PC版本号",
  "equipment": "设备",
  "currentVersion": "当前版本",
  "versionNumber": "版本号",
  "startIp": "起始IP",
  "endIp": "结束IP",
  "controlType": "控制类型",
  "statusIp": "ip状态",
  "content": "内容",
  "Date": "日期",
  "BatchDeleting": "批量删除",
  "title": "标题",
  "ReleaseTime": "发布时间",
  "BulletinTitle": "公告标题",
  "BulletinContent": "公告内容",
  "SiteID": "站点ID",
  "AddSiteID": "添加站点",
  "FullStationMaintenance": "全站维护",
  "siteName": "站点名称",
  "Mark": "标示",
  "domain": "域名",
  "LineOfVideo": "视讯额度",
  "Add/LiveTime": "添加/上线时间",
  "ModuleManagement": "模块管理",
  "Finance": "财务",
  "GoOnline": "上线",
  "negative": "负数",
  "multistation": "多站点",
  "Reception": "前台",
  "data": "数据",
  "Navigation": "导航",
  "DefaultSiteSettings":"默认站点设置",
  "SiteFrontDeskID":"站点前台ID",
  "DomainNameUpperLimit":"域名上限",
  "ExceedTheUpperLimit":"超过上限",
  "Yuan/unit":"元/个",
  "ChoiceOfSetMeal":"套餐选择",
  "AmendAccountOpenAccount":"修改开户人账号",
  "PermissionConfiguration":"权限配置",
  "carte":"菜单",
  "RoleState":"角色状态",
  "SiteInformation":"站点资料",
  "DomainNameLine":"域名上线",
  "ExceedingTheUpperLimit":"超过上限收费",
  "PCDomain":"PC域名",
  "PhoneDomain":"手机域名",
  "PayDomain":"支付域名",
  "FunctionalPermissions":"功能权限",
  "NewPlatformMenu":"新增平台菜单",
  "Internationalization":"国际化",
  "UploadIcon":"上传Icon",
  "NewAgentMenu":"新增代理菜单",
  "Hierarchy":"所属层级",
  "Platform / agent":"平台/代理",
  "PlatformMenuModification":"平台菜单修改",
  "SuperiorMenu":"上级菜单",
  "ProxyMenuModification":"代理菜单修改",
  "NewGoods":"新增商品",
  "ModifyGoods": "修改商品",
  "ModificationFunction":"修改功能",
  "ReviseTheSetMeal":"修改套餐",
  "AccountQuery":"账户查询",
  "IsItOpen":"是否开启",
  "Submit":"提交",
  "DownloadLinkAddress":"下载链接地址",
  "AddressEditing":"地址编辑",
  "JSVersionNumber-WEP":"JS版本号-WEP",
  "JSVersionNumber-PC":"JS版本号-PC",
  "WAPAvailableVersionNumber":"WAP可用版本号",
  "ComparisonWithTheBasicVersion":"与基本版本一致性比较",
  "particulars":"详情",
  "BaseFilePath":"基础文件路径",
  "CurrentVersionPath":"当前版本路径",
  "PCEndAvailableVersionNumber":"PC端可用版本号",
  "JSVersionNumber-TotalTable":"JS版本-总表",
  "IPSwitchingOperation":"IP开关操作",
  "IPWhiteList":"ip白名单",
  "AddIPOperation":"添加IP操作",
  "ClientBackstage":"客户后台",
  "AgentBackstage":"代理后台",
  "WAP":"WAP端",
  "ModifyTheIPOperation":"修改ip操作",
  "AddIPWhiteList":"添加IP白名单",
  "ModifyTheIPWhiteList":"修改ip白名单",
  "NewAnnouncement":"新增公告",
  "Package":"套餐",
  "QuotaOperation":"额度操作",
  "SelectType":"选择类型",
  "CurrentQuota":"当前额度",
  "OperationAmount":"操作金额",
  "deposit":"存款",
  "Debit":"扣款",
  "PreLoanDeposit":"预借存款",
  "MainDomainName":"主域名",
  "BackgroundDomainName":"后台域名",
  "TotalNumberOfDomainNames":"域名总数",
  "DoYouDownloadApp":"是否下载app",
  "yes":"是",
  "NO":"否",
  "SiteType(the financial operation of this column)":"站点类型(此栏财务操作)",
  "line":"线路",
  "EditSite":"编辑站点",
  "StateModification":"状态修改",
  "open":"开启",
  "Close":"关闭",
  "domainName":"域名",
  "AddAgent":"添加代理",
  "One-keyGenerationOfThree-levelAgent":"一键生成三级代理",
  "ModifyTheSite":"修改站点",
  "Category":"所属类别",
  "ShareholderName":"股东名称",
  "ShareholderAccount":"股东账号",
  "ShareholdersNotes":"股东备注",
  "GeneralName":"总代名称",
  "GeneralAccount":"总代账号",
  "GeneralRemark":"总代备注",
  "ProxyName":"代理名称",
  "ProxyAccount":"代理账号",
  "AgentNotes":"代理备注",
  "InitialNonStratifiedData":"初始未分层数据",
  "ViewLevelSetting":"查看层级设定",
  "HierarchyNumber":"层级编号",
  "HierarchyName":"层级名称",
  "Described":"描述",
  "MobileLevel":"移动层级",
  "HierarchyInformation":"层级信息",
  "HierarchySelection":"层级选择",
  "depositDate":"存入日期",
  "mode":"方式",
  "autoRefresh":"自动刷新",
  "AmountAlarm":"金额报警",
  "ProxyID":"代理ID",
  "TransactionCategory":"交易类别",
  "DateOfTransaction":"交易日期",
  "QueryTime":"查询时间",
  "Proportionate":"抽成比例",
  "VideoTransferLine":"视讯转出额度",
  "increaseInThePurse":"钱包增加额度",
  "TurnOutTheNumberoOfPens":"转出笔数",
  "VideoTransferToTheAmount":"视讯转入额度",
  "PurseDeductions":"钱包扣除额度",
  "NumberOfPens":"转入笔数",
  "Result":"结果",
  "Total":"总计",
  "AmountRecord":"额度记录",
  "VideoType":"视讯类型",
  "Type of transaction":"交易类型",
  "PurseBalance":"钱包余额",
  "RechargeAmount":"充值金额",
  "StateOfPayment":"支付状态",
  "PaymentType":"支付类型",
  "ThirdPartyManagement":"第三方管理",
  "BankCardManagement":"银行卡管理",
  "ThirdPartyNames":"第三方名字",
  "AccountAccount":"支付账号",
  "StatePayPalAccount":"国付宝账号",
  "TreasurePaymentTerminalNumber":"宝付终端号",
  "topClass":"所在层级",
  "BankCardName":"银行卡名字",
  "BankCardAccountNumber":"银行卡账号",
  "Payee":"收款人",
  "BankAddress":"开户行地址",
  "ThirdPartyInformation":"第三方信息",
  "ThirdPartyType":"第三方类型",
  "BankCardInformation":"银行卡信息",
  "BankAccount":"开户行",
  "Third party information -- editors":"第三方信息--编辑",
  "Bank card information -- editors":"银行卡信息--编辑",
  "timeZone":"时区",
  "TotalNumberOfPen":"总笔数",
  "WinTheNumberOfPen":"赢笔数",
  "TotalInvestment":"总投注",
  "EffectiveBetting":"有效投注",
  "Payout":"派彩",
  "Subtotal":"小计",
  "List of preferential statistics":"优惠统计列表",
  "Timed task":"定时任务",
  "Re - Statistics":"重新统计",
  "PreferentialAmount":"优惠金额",
  "The list of statistics in China":"入款统计列表",
  "Receipt":"入款方式",
  "ShareholderID":"股东ID",
  "TotalGenerationID":"总代ID",
  "TheAmountOfMoney":"入款金额",
  "Summary of entry and exit items":"出入款项目汇总",
  "Date interval":"日期区间",
  "ThisWeek":"本周",
  "income":"收入",
  "OnlinePayment":"线上支付",
  "ManualDeposit":"人工存入",
  "Deducted money for members":"会员出款被扣金额",
  "Income total":"收入总计",
  "expenditure":"支出",
  "Member out of money":"会员出款",
  "Give preferential treatment":"给予优惠",
  "Artificially put forward":"人工提出",
  "Return water":"给予返水",
  "Total expenditure":"支出总计",
  "Actual profit and loss":"实际盈亏",
  "Account total":"账目总计",
  "OG time":"OG时间",
  "Other time":"其他时间",
  "Module selection":"模块选择",
  "Click unfold":"点击展开",
  "ReverseSelection":"反选",
  "AddReminders":"添加催款",
  "bank":"银行",
  "Down time":"下发时间",
  "Customer payment status":"客户支付状态",
  "Has it been delivered":"是否已经交付",
  "Have money":"已催款",
  "Confirm the payment":"确认付款",
  "press for money":"催款",
  "Receivable bank information":"收款银行信息",
  "Opening bank network":"开户行网点",
  "ThePreviousPeriod":"上期",
  "Pattern":"模式",
  "Game selection":"游戏选择",
  "textMoreOne":"此选项为查询后是否导出总报表,选是才会显示导出总报表按钮",
  "Billing status":"账单状态",
  "NumberOfPeriods":"期数",
  "Billing":"下发账单",
  "website":"网站",
  "Project":"项目",
  "TheAmountOf":"金额",
  "LastMonthsNegative":"上月负数",
  "Condition":"条件",
  "NegativeAmount":"负数额度",
  "Accounts receivable":"應收",
  "ShouldBeBuckled":"应加应扣",
  "Proportion":"比例",
  "This month should be added":"本月应加",
  "textMoreTwo":"客户接到财务对账单，三天内如有数据疑问请联系财务专员，财务专员SKYPE:pk.finance",
  "textMoreThree":"如无疑问，汇款前请找财务专员索取最新汇款账号，感谢您们的支持，PK娱乐平台团队致敬",
  "textMoreFour":"汇款账号发出后，半小时内没汇好款，要汇款之前请再联系我们确认汇款账号，以免有变动",
  "ProxyType":"代理类型",
  "AccountQuerys":"账号查询",
  "loginIP":"登录IP",
  "accountType":"账号类型",
  "Handicap":"盘口",
  "View member information":"查看会员资料",
  "Country":"国家",
  "address":"地址",
  "Registered IP":"注册IP",
  "lastLogin":"最后登录",
  "Logon log":"登录日志",
  "Operation date":"操作日期",
  "message":"讯息",
  "login time":"登入时间",
  "IP position":"IP位置",
  "Record":"记录",
  "Operating income":"入款操作",
  "The section selection":"入款选择",
  "Depositor":"存款人",
  "Deposit method":"存款方式",
  "Amount and discount":"存入金额与优惠",
  "Total deposit":"存入总额",
  "Money operation":"出款操作",
  "Raise the amount":"提出额度",
  "Service Charge":"手续费",
  "Administrative fee":"行政费",
  "Amount of money":"出款金额",
  "Account balance":"账户余额",
  "Preferential deduction":"优惠扣除",
  "Date of payment":"出款日期",
  "audit":"稽核",
  "changeDate":"更改日期",
  "Audit list":"稽核列表",
  "StartDate":"开始时间",
  "Bulletin key management":"公告密钥管理",
  "SitePaymentID":"站点支付ID",
  "Pay ID":"支付ID",
  "public":"公用",
  "key":"密匙",
  "server public key":"服务器公钥",
  "Account category":"账号类别",
  "Folder cipher":"文件夹密码",
  "Front desk":"前台站点",
  "Self help switch":"自助优惠开关",
  "Audit time":"审核时间",
  "Activity category":"活动类别",
  "Reasons for application":"申请理由",
  "Donation amount":"赠送金额",
  "Application status":"申请状态",
  "Details of preferential application":"优惠申请详情",
  "Activity title":"活动标题",
  "Activity content":"活动内容",
  "By remark":"通过备注",
  "Normalization":"常态性稽核",
  "Comprehensive code checking":"综合打码稽核",
  "Check, code quantity":" 稽核,打码量",
  "Website Name":"网站名称",
  "Preferential setting":"优惠设置",
  "Input site ID":"输入站点ID",
  "Inquiries":"年月份查询",
  "Event":"事件",
  "Defection interval":"反水区间",
  "rise":"起",
  "So far":"迄",
  "Number / amount":"人数/金额",
  "Creation date":"创建日期",
  "creator":"创建者",
  "Comprehensive code multiplier":"综合打码倍数",
  "Inquire detail":"查询明细",
  "Public projectile frame":"公共弹框",
  "H5 animation":"H5动画",
  "Network name":"网络名称",
  "Bulletin board configuration":"公告弹框配置",
  "System username":"系统用户名",
  "Third party platform username":"第三方平台用户名",
  "User balance":"用户余额",
  "add template":"添加模板",
  "name":"名称",
  "Add video template":"添加视讯模板",
  "Template name":"模板名称",
  "Template sequence number":"模板序号",
  "Modifying the video template":"修改视讯模板",
  "Membership import": "会员导入",
 "membershipStatistics":"会员统计",
  "flowStatistics":"流量统计",
  "commodityStatistics":"商品统计",
  "transactionStatistics":"交易统计",
  "redPacketSupplement":"红包补数据",
 "threePartyOperations":"三方操作列表"
}`

var CNLangsAgency = `{
  "Red packet management": "红包管理",
  "Red packet view": "红包查看",
  "Add red envelopes": "添加红包",
  "Red packet setting": "红包设定",
  "Red packet style management": "红包样式管理",
  "templateManagement": "模板管理",
  "redManagement": "红包管理",
  "lineStatus": "登录状态",
  "PROJECTS": "项目",
  "Msgs": "封邮件",
  "Notify": "通知",
  "Tasks": "任务",
  "Recent projects": "最近项目",
  "Find reports and more": "查找报告和更多",
  "john.doe": "john.doe",
  "Dashboard": "仪表板",
  "Angular Stuff": "角的东西",
  "UI Bootstrap": "UI引导",
  "Get Locale JSON": "获取地点JSON",
  "Inbox": "收件箱",
  "Graphs": "图",
  "Flot Chart": "海军报图",
  "Morris Charts": "莫里斯图表",
  "Inline Charts": "内嵌图表",
  "Dygraphs": "Dygraphs",
  "Tables": "表",
  "Normal Tables": "普通表",
  "Data Tables": "数据表",
  "Forms": "形式",
  "Smart Form Elements": "智能表单元素",
  "Smart Form Layouts": "智能表布局",
  "Smart Form Validation": "智能表单验证",
  "Bootstrap Form Elements": "引导表单元素",
  "Bootstrap Form Validation": "引导表单验证",
  "Outlook": "前景",
  "Cool Features": "很酷的功能",
  "App Views": "应用程序浏览",
  "Form Plugins": "表格插件",
  "Wizards": "奇才",
  "Bootstrap Editors": "引导编辑",
  "Dropzone": "悬浮窗",
  "UI Elements": "UI元素",
  "General Elements": "一般信息",
  "E-Commerce": "电子商务",
  "Buttons": "按钮",
  "Icons": "图标",
  "Font Awesome": "字体真棒",
  "Glyph Icons": "字形图标",
  "Grid": "格",
  "Tree View": "树视图",
  "Nestable Lists": "嵌套列表",
  "JQuery UI": "JQuery用户界面",
  "Typography": "活版印刷",
  "Six Level Menu": "六级菜单",
  "Item #2": "Item #2",
  "Sub #2.1": "Sub #2.1",
  "Item #2.1.1": "Item #2.1.1",
  "Expand": "扩大",
  "File": "文件",
  "Delete": "删除",
  "Agreement": "协议",
  "Item #3": "项目＃ 3",
  "3rd Level": "第三层",
  "Calendar": "日历",
  "Widgets": "小工具",
  "Gallery": "画廊",
  "GMap Skins": "GMAP皮肤",
  "Miscellaneous": "杂",
  "Other Pages": "其他页",
  "Forum Layout": "版块布局",
  "Profile": "简介",
  "Timeline": "时间线",
  "Pricing Tables": "价格表",
  "Invoice": "发票",
  "Login": "登录",
  "Not Login": "未登录",
  "Register": "寄存器",
  "Locked Screen": "锁定屏幕",
  "Locked": "锁定",
  "Error 404": "错误404",
  "Error 500": "错误500",
  "Blank Page": "空白页",
  "Email Template": "电子邮件模板",
  "Search Page": "検索ページ",
  "CK Editor": "CK编辑器",
  "SmartAdmin Intel": "SmartAdmin英特尔",
  "Different Versions": "不同版本",
  "Documentation": "文件",
  "Bug Tracker": "Bug跟踪",
  "Mail": "邮件",
  "Maps": "地图",
  "My Profile": "我的简历",
  "Page Header": "页眉",
  "Subtitle": "字幕",
  "Permission Grouping": "权限分组",
  "Admin Account": "管理员账号",
  "Admin Log": "管理日志",
  "Dealer Management": "经销商管理",
  "Commodity": "商品管理",
  "Sort Management": "分类管理",
  "Release goods": "发布商品",
  "Site List": "站点列表",
  "Create Site": "创建站点",
  "Order Management": "订单管理",
  "Settlement": "结算管理",
  "Pending application": "待结算申请",
  "Settlement record": "已结算记录",
  "Payment Management": "支付管理",
  "Customer Management": "会员管理",
  "Customer Info": "会员资料",
  "Advertising state": "广告状态",
  "Search": "搜索",
  "AddMore": "添加",
  "Preview of advertising": "广告预览",
  "Internal chain address": "内链地址",
  "GroupName": "分组名称",
  "Shareholder name": "股东名称",
  "Administrator Management": "管理员管理",
  "Administrator Number": "管理员管理",
  "Status": "状态",
  "Remarks": "备注",
  "PreviousPage": "上一页",
  "NextPage": "下一页",
  "Edit": "编辑",
  "Order List": "订单列表",
  "Classification of goods": "商品分类",
  "Payment channel": "支付渠道",
  "State": "状态",
  "Agent num": "代理人数",
  "Source of money": "出款来源",
  "Automatic hair down": "自动下发",
  "Modify agent account": "修改代理账号",
  "Please enter the name of the commodity": "请输入商品名称",
  "Commodity name": "商品名称",
  "Unit price / quantity": "单价/数量",
  "Owned dealer": "所属经销商",
  "Order status": "订单状态",
  "General Commission": "总佣金",
  "Home": "首页",
  "Settlement management": "结算管理",
  "Settlement request": "待结算申请",
  "List of settlement requests": "待结算申请列表",
  "Start time of order creation": "订单创建开始时间",
  "Order creation end time": "订单创建结束时间",
  "Dealer name search": "经销商名称搜索",
  "Add line detection address": "添加线路检测地址",
  "Order ID": "订单ID",
  "Dealer name": "经销商名称",
  "Application time": "提出申请时间",
  "Balance of settlement": "可结算余额",
  "Settlement amount": "结算金额",
  "Administration": "管理",
  "Payment interface management": "支付接口管理",
  "Payment interface list": "支付接口列表",
  "Add interface": "添加接口",
  "Service provider logo": "服务商logo",
  "Interface name": "接口名称",
  "ID": "ID",
  "Flow amount": "流水金额",
  "Site": "站点",
  "Query time": "查询时间",
  "Please enter the membership account": "请输入会员账号",
  "Time zone": "时区",
  "Customer nickname": "会员昵称",
  "List of customer management": "会员管理列表",
  "Customer source": "客户来源",
  "Customer ID": "会员ID",
  "Member": "会员",
  "Subordinate site": "所属站点",
  "Adding preferential activities": "添加优惠活动",
  "Preferential width": "优惠宽度",
  "A turnover": "交易额",
  "integral": "积分",
  "operation": "操作",
  "Bank owner": "卡主名字",
  "Bank id": "银行id",
  "Administrator account": "管理员账号",
  "Select group name": "选择分组名称",
  "Administrator account search": "请输入搜索关键字",
  "Accounts": "账号",
  "First": "首次",
  "Raise the amount of cash": "提现额度",
  "Creation Time": "创建时间",
  "Modification time": "修改时间",
  "Set up to be valid": "置为有效",
  "Null and void": "置为无效",
  "Dealer ID": "经销商ID",
  "Distributor": "经销商",
  "Total goods": "商品总数",
  "Goods": "商品",
  "Click unfold": "点击展开",
  "Total customer": "会员总数",
  "Total order": "订单总数",
  "Total transaction": "交易总额",
  "Total distribution": "分销商总数",
  "Distributor order totals": "分销商订单总数",
  "Distributor transaction volume": "分销交易总额",
  "Total settlement": "已结算总额",
  "Registration time": "注册时间",
  "Settlement amount to be processed": "待处理结算(数量)",
  "Site management": "站点管理",
  "Choose dealers": "选择经销商",
  "site": "站点",
  "ChildAccount": "子账号",
  "ChildAccount Power": "子账号权限",
  "MemberManagement": "会员管理",
  "FundManagement": "资金管理",
  "MarginManagement": "保证金管理",
  "ReCommisManagement": "返佣管理",
  "RebateManagement": "返点管理",
  "Announcement": "公告管理",
  "SiteChoice": "站点选择",
  "Only write a domain name": "只写域名",
  "Return address": "返回地址",
  "Business ID": "商户ID",
  "Address written after payment": "支付成功后写的地址",
  "Adding ad in the station": "添加站内广告",
  "Window advertising setting": "弹窗广告设置",
  "UserName": "用户名",
  "DividedManagement": "分成分组管理",
  "DealerQuantity": "经销商数量",
  "DivideInto": "分成比例",
  "CreatePacket": "创建分组",
  "SortType": "排序类型",
  "Enable": "是否启用",
  "DealerCommission": "经销商返佣比",
  "DistributorRegistration": "分销商注册设定",
  "Dealer grouping": "经销商权限分组",
  "AdministratorGrouping": "管理员数量",
  "addDelaer": "添加经销商",
  "DistributorName": "分销商名称",
  "OrderDetails": "订单详情",
  "Check all": "全选",
  "Batch pass": "批量通过",
  "Normal code": "常态打码",
  "Co deduction": "共扣除",
  "Loan quota": "放款额度",
  "Administrative expenses are required to be deducted": "需扣除行政费用",
  "Amount of deductions": "需扣除金额",
  "Adopt": "通过",
  "Level": "级别",
  "Name": "名称",
  "Game selection": "游戏选择",
  "Balance": "余额",
  "Cash record ID": "现金记录ID",
  "Trading platform": "交易平台",
  "Date of transaction": "交易日期",
  "Transfer out of the project": "转出项目",
  "Transfer to the project": "转入项目",
  "Transfer out amount": "转出金额",
  "Please enter an integer": "请输入整数",
  "Operator": "操作人",
  "Subtotal": "小计",
  "Total": "总计",
  "Auditor": "审核人",
  "Reasons for rejection": "驳回原因",
  "Member source": "会员来源",
  "distributor": "分销商",
  "Online search": "在线搜索",
  "Member account": "会员账号",
  "Please select the hierarchy": "请选择层级",
  "Distributors": "所属分销商",
  "System balance": "系统余额",
  "Online": "是否在线",
  "Member registration settings": "会员注册设定",
  "members registered": "是否用户会员注册",
  "Tourist registration": "游客注册",
  "Registration requires mailbox": "注册需邮箱",
  "Are mailbox repeats allowed": "是否允许邮箱重复",
  "Registration requires QQ": "注册需要QQ",
  "Are you allowed to repeat QQ": "是否允许QQ重复",
  "Registration requires phone": "注册需要手机号",
  "Are you allowed to repeat phone": "是否允许手机号重复",
  "Registration requires birth date": "注册需要出生日期",
  "Open authentication code": "开启验证码",
  "Done": "完成",
  "Open": "开启",
  "Member order list": "会员订单列表",
  "Commodity type": "商品类型",
  "Consumption": "消费",
  "Settlement method": "结算方式",
  "Mode": "方式",
  "Order number": "订单号",
  "Order time": "订单时间",
  "Transaction amount": "交易金额",
  "Purchase amount": "购买优惠金额",
  "Preferential amount": "优惠金额",
  "Add packet": "添加分组",
  "Packet information": "分组信息",
  "Privilege management": "权限管理",
  "Functional module": "功能模块",
  "Function selection": "功能选择",
  "Module enabled": "是否启用模块",
  "Create success": "创建成功",
  "Create packet completion": "创建分组完成，可在管理员管理模块添加管理员到新创建的分组；在权限管理中可对分组进行权限管理。",
  "See": "查看",
  "Return list": "返回列表",
  "Previous step": "上一步",
  "Next step": "下一步",
  "Create schedule": "创建进度",
  "Add Account": "添加帐号",
  "accounts": "帐号",
  "Password": "密码",
  "Permission grouping": "权限分组",
  "Status enabled disabled": "状态启用禁用",
  "Enables": "启用",
  "Disable": "禁用",
  "Confirm": "确认",
  "Cancel": "取消",
  "Preservation": "保存",
  "Journal": "日志",
  "Time": "时间",
  "Operation record": "操作记录",
  "Edit account": "编辑帐号",
  "Submit successfully": "提交成功",
  "View grouping": "查看分组",
  "Power": "权限",
  "Total administrator": "管理员总数",
  "Member list": "成员列表",
  "Operating time": "操作时间",
  "Depositor account number": "存款人账号",
  "Deposit time": "存款时间",
  "Total deposit": "存入总额",
  "The main deposit bank card": "入款银行卡主",
  "Deposit bank card number": "入款银行卡号",
  "First deposit": "首存",
  "Grounping": "分组",
  "Confirmed": "已确认",
  "Has been canceled": "已取消",
  "Permission view": "权限查看",
  "Basic information": "基础信息",
  "Confirm password": "确认密码",
  "Please enter your password again": "请再次输入密码",
  "Divide into groups": "分成分组",
  "Modify dealer": "修改经销商",
  "Submission": "提交",
  "Confirm submission": "确定提交",
  "Modified grouping": "修改分成分组",
  "Enable proxy registration": "是否启用代理注册",
  "Primary dealer": "一级经销商",
  "Two dealer": "二级经销商",
  "Please enter": "请输入",
  "Distributor quantity": "分销商数量",
  "Distributor split ratio setting": "分销商分成比设定",
  "My ratio": "我的占比",
  "Subordinate ratio": "下级占比",
  "Packet creation": "分成分组创建",
  "Modify": "修改",
  "Please enter the name of the applicant": "请输入申请人名称",
  "Applicant ID": "申请人ID",
  "Applicant name": "申请人名称",
  "Subordinate": "所属上级",
  "CAAC Certificate No": "证件号",
  "Mailbox": "邮箱",
  "QQ": "QQ",
  "E-MAIL": "E-MAIL",
  "Cell-phone number": "手机号",
  "Management": "管理",
  "Child account list": "子账号列表",
  "Unit price": "单价售价",
  "Number of shelves": "上架次数",
  "Commission amount": "返佣金额",
  "Inventory quantity": "库存数量",
  "Batch shelves": "批量上架",
  "Batch Operation": "批量操作",
  "Details": "详情URL",
  "Are goods allowed on shelves": "是否允许商品上架",
  "Release": "发布",
  "(unit: yuan)": "（单位：元）",
  "Chinese: apples": "中文：苹果",
  "(unit: Unit)": "（单位：个）",
  "Class A": "一级",
  "Second level": "二级",
  "Three": "三级",
  "Commodity details page": "商品详情页面",
  "View details of the goods": "查看商品详情",
  "View commodity information": "查看商品信息",
  "Commodity attribute": "商品属性",
  "Publication quantity": "发布数量",
  "View categories": "查看分类",
  "Classified ID": "分类ID",
  "Category name": "分类名称",
  "Classification description": "分类描述",
  "Add categories": "添加分类",
  "Modify goods": "修改商品",
  "Site name": "站点名称",
  "Site information": "站点信息",
  "Tip": "提示",
  "Select site status": "请选择站点状态",
  "Select site": "选择站点",
  "Selection interface": "选择界面",
  "Select the dealer or manually enter the dealer name": "请选择经销商或手动输入经销商名称",
  "PC domain name": "PC域名",
  "Please enter the PC domain name": "请输入PC域名",
  "WAP domain name": "WAP域名",
  "WAP bottom text": "wap底部文案",
  "Please fill in the WAP bottom copy": "请填写wap底部文案",
  "Please fill in the WAP bottom link": "wap底部按钮链接",
  "WAP bottom button link": "为空默认不显示",
  "WAP bottom button name": "wap底部按钮名称",
  "Please enter the WAP domain name": "请输入WAP域名",
  "SSI certificate": "SSI证书",
  "Select file": "选择文件",
  "Click Add domain name and certificate customer service information": "点击添加域名及证书客服信息",
  "WeChat": "微信",
  "Telephone": "电话",
  "Email": "电邮",
  "Customer service hotline": "客服热线",
  "Easy to remember domain name": "易记域名",
  "Online customer service": "在线客服",
  "Please fill in the domain name": "请填写域名",
  "Please fill in the notes": "请填写备注",
  "Please fill in the customer service phone": "请填写客服电话",
  "Customer service information": "客服信息",
  "Modify site information": "修改站点信息",
  "WAP top color": "wap顶部颜色",
  "APP download link": "APP下载链接",
  "EditAccount": "编辑账号",
  "EditGroup": "编辑分组",
  "LookPower": "查看权限分组",
  "MarginApplication": "保证金申请",
  "Order information": "订单信息",
  "Commodity information": "商品信息",
  "Single product discount": "单品优惠",
  "Quantity purchased": "购买数量",
  "Buy discount": "购买优惠",
  "Purchase amount1": "购买金额",
  "Operation type": "操作类型",
  "Deposit amount": "存款金额",
  "Deposit preferences": "存款优惠",
  "Remittance discount": "汇款优惠",
  "Comprehensive code checking": "综合打码稽核",
  "Comprehensive code": "综合打码",
  "Deposit": "存入",
  "Access money": "存取款",
  "Sort": "排序",
  "Deposit / withdrawal amount": "存/取款金额",
  "Amount of withdrawals": "取款金额",
  "Withdrawal Project": "取款项目",
  "Member name": "会员名称",
  "Commission list": "返佣列表",
  "Commission setting": "返佣设定",
  "Parent account": "父级账号",
  "Recommended number": "推荐人数",
  "Rebate list": "返点列表",
  "Margin application": "保证金申请",
  "Please enter a single number": "请输入单号",
  "New application": "新建申请",
  "Apply for an account": "申请账号",
  "Application amount": "申请金额",
  "Date of application": "申请日期",
  "Remittance mode": "汇款方式",
  "Report details": "报表详情",
  "Export EXCEL": "导出EXCEL",
  "Site other": "站别",
  "User information": "用户信息",
  "Recharge warning": "充值预警",
  "Recharge application": "充值申请",
  "Recharge alert settings": "充值预警设定",
  "Debit note number": "扣款单号",
  "Deductible amount": "扣除金额",
  "Date of deduction": "扣款日期",
  "Associated single number": "关联单号",
  "Third party payment": "第三方支付",
  "Third party": "第三方",
  "Bank card transfer": "银行卡转账",
  "Bank remittance": "银行汇款",
  "Remittance form": "汇款表单",
  "Platform": "平台管理",
  "Girokonto": "转账账号",
  "Collection account": "收款账号",
  "Deposit Amount": "存入金额",
  "Other concessions": "其他优惠",
  "Deposit in the total amount": "存入总金额",
  "Select the accounts receivable account": "选择收款账号",
  "Amount of money": "金额",
  "Total amount": "总金额",
  "Total number of pen": "总笔数",
  "Transfer amount": "转账金额",
  "Transfer time": "转账时间",
  "Trading time": "交易时间",
  "Basic data editing": "基本资料编辑",
  "Bank name": "银行名称",
  "Advertisement name": "广告名称",
  "Please enter the agent account number": "请输入代理商账号",
  "Transfer card number": "转账卡号",
  "Collection card number": "收款卡号",
  "Running odd numbers": "流水单号",
  "Rebate amount": "返点总额",
  "Set point": "返点设定",
  "Check rebate": "查看返点",
  "Report form": "报表",
  "Start time": "开始时间",
  "End time": "结束时间",
  "Before logging in": "登录前",
  "After logging in": "登录后",
  "Advertising links": "广告链接",
  "Whether or not the internal chain is an internal chain": "是否为内链",
  "Today": "今日",
  "Yesterday": "昨日",
  "Last week": "上周",
  "This week": "本周",
  "This period": "本期",
  "Do not cross month query": "请勿跨月份查询",
  "Actual profit and loss": "实际盈亏",
  "Display condition": "显示条件",
  "Whether to enable membership promotion": "是否启用会员推广",
  "RMB": "元",
  "People number": "人",
  "Number of time": "次",
  "The amount of income": "入款金额",
  "The number of income": "入款人数",
  "The times of income": "入款次数",
  "Total amount of outcome": "出款总额",
  "The number of outcome": "出款人数",
  "The times of outcome": "出款次数",
  "Income": "收入",
  "Income amount": "收入金额",
  "Transaction number": "交易人数",
  "Transaction pen number": "交易笔数",
  "Member out of money": "会员出款",
  "Expenditure": "支出",
  "Details of expenditure": "支出明细",
  "Number and period in 2016": "2016年月幅期数",
  "Number and period in 2017": "2017年月幅期数",
  "Report type": "报表类型",
  "New announcement": "新建公告",
  "Title": "标题",
  "Title color": "标题颜色",
  "Background color": "背景颜色",
  "Title bar color": "标题栏颜色",
  "Content": "内容",
  "Release time": "发布时间",
  "Publish account": "发布账号",
  "Display effect": "展示效果",
  "Block": "方框",
  "Hollow": "镂空",
  "Position": "位置",
  "Type": "类型",
  "Maximum width value": "最大宽度值",
  "Dealer account": "经销商账号",
  "Return commission setting": "返佣金设定",
  "Return commissions and online": "返佣金上线",
  "Announcement type": "公告类型",
  "Please select": "请选择",
  "Whether or not to retire": "是否退佣",
  "Write in": "写入",
  "Sports name": "体育名称",
  "Please input password": "请输入密码",
  "Please input confirm password": "请输入确认密码",
  "Announcement heading": "公告标题",
  "Announcement content": "公告内容",
  "Subordinate group": "所属分组",
  "Recording time": "记录时间",
  "IP address": "IP地址",
  "code": "代码",
  "Copywriting code": "文案代码",
  "Copywriting headlines": "文案标题",
  "Copywriting type": "文案类型",
  "Use a contact form": "使用联络表单",
  "Proxy login": "代理登录",
  "Copywriting category": "文案类别",
  "Operation behavior": "操作行为",
  "Administrator operation": "管理员操作",
  "Grade": "等级",
  "SettlementRequest": "保证金申请",
  "DistributorBalance": "分销商余额查看",
  "Account management": "账号管理",
  "Distributor list": "分销商列表",
  "Distributor Application List": "分销商申请列表",
  "Distributor application setting": "分销商申请设定",
  "Transaction management": "交易管理",
  "Goods shelves (dealers)": "商品上架（经销商）",
  "List of goods on shelves": "上架商品列表",
  "Rebate settings": "返利设置",
  "SystemSettings": "系统设置",
  "System": "系统",
  "Member registration management": "会员注册管理",
  "Member grouping management": "会员分组管理",
  "Distributor balance view": "分销商余额查看",
  "ReportForm": "报表管理",
  "A_1": "会员管理",
  "A_1_1": "正式账号",
  "A_1_2": "带玩账号",
  "A_1_3": "添加带玩",
  "A_2": "股东管理",
  "A_3": "总代理管理",
  "A_4": "代理管理",
  "A_5": "子账号",
  "A_6": "会员注册设定",
  "A_7": "代理申请管理",
  "A_8": "体系查询",
  "A_9": "层级管理",
  "A_10": "开户人管理",
  "Add Heriy": "添加层级",
  "Modify Heriy": "添加层级",
  "Bank": "出款银行",
  "Modify Agent Info": "修改代理资料",
  "Agent Domain": "代理域名",
  "Domain": "域名",
  "Add time": "添加时间",
  "DepositsWithdrawals": "人工存款",
  "HistoryQuery": "出入账目记录",
  "QuotaConversion": "额度转换",
  "MarginReplacement": "额度转换记录",
  "entryAndExit": "出入账目汇总",
  "CashManagement": "出款管理",
  "Refresh immediately": "立即刷新",
  "MoneyManagement": "入款管理",
  "companyInChina": "公司入款",
  "ChinaOnline": "线上入款",
  "Immediate": "即时稽核查询",
  "auditLog": "稽核日志",
  "Audit": "稽核",
  "Code amount": "打码量",
  "Normalization": "常态性稽核",
  "Deposit item": "存款项目",
  "PaymentSetting": "支付设定",
  "BankElimination": "出款银行剔除",
  "DepositBankSet": "入款银行设定",
  "IncomeExcludingBank": "入款银行剔除",
  "bankElimination": "第三方银行剔除",
  "OnlinePaymentSetup": "线上支付设定",
  "PaymentParameterSetting": "支付参数设定",
  "AutomaticCashSetting": "自动出款设定",
  "Automatic payment": "自动出款",
  "Is it going down": "是否下发",
  "Three party hair": "三方下发",
  "Online payment": "线上支付",
  "Give preferential treatment": "给予优惠",
  "Manual deposit": "人工存入",
  "Artificial presentation": "人工提现",
  "Deducted money for members": "会员出款被扣金额",
  "Project summary": "项目汇总",
  "Turn out platform": "转出平台",
  "Transfer to the platform": "转入平台",
  "Conversion amount": "转换金额",
  "Lose a single time": "掉单时间",
  "Start date": "开始日期",
  "End date": "结束日期",
  "Transaction category": "交易类别",
  "Given the defection": "给予反水",
  "Drop out application": "掉单申请",
  "CashSystem": "现金流水",
  "MemberAnalysis": "会员分析",
  "Analysis": "出入款分析",
  "MemberInquiries": "会员查询",
  "PurchaseAnalysis": "购买分析",
  "PreferentialAnalysis": "退水分析",
  "ValidMembershipList": "有效会员列表",
  "Effective member": "有效会员",
  "CommissionStatistics": "退佣统计",
  "AgentRetirementSetting": "代理退佣设定",
  "PeriodManagement": "期数管理",
  "FeeSetting": "手续费设定",
  "Service Charge": "手续费",
  "Administrative fee": "行政费",
  "Amount out of money": "出款金额",
  "Account balance": "账户余额",
  "Preferential deduction": "优惠扣除",
  "Date of payment": "出款日期",
  "CommissionInquiry": "退佣查询",
  "MemberBalance": "会员余额统计",
  "PreferentialCalculation": "优惠计算",
  "SetPreferential": "返点优惠设定",
  "PreferentialInquiry": "优惠查询",
  "PreferentialStatistics": "优惠统计",
  "SelfDefectionQuery": "自助反水查询",
  "MembershipReturns": "会员返佣",
  "CommissionSetting": "返佣查询",
  "Query": "查询",
  "RebateSetting": "返佣优惠设定",
  "MemberPromotionInquiries": "会员推广查询",
  "MemberPromotionSettings": "会员推广设定",
  "QuotaStatistics": "额度统计",
  "RechargeRecord": "充值记录",
  "DropList": "掉单列表",
  "QuotaRecharge": "额度充值",
  "QuotaRecord": "额度记录",
  "AnnouncementInformation": "公告信息",
  "SystemAnnouncement": "系统公告",
  "MemberMessage": "会员消息",
  "ReleaseNewMessages": "发布新消息",
  "RegistrationCouponTemplates": "注册优惠消息模板",
  "LatestNews": "最新消息",
  "LogManagement": "日志管理",
  "MemberLogin": "会员登录",
  "AdministratorLogin": "管理员登录",
  "Choose China Merchants": "选择入款商户",
  "China Merchants": "入款商户",
  "OperationLog": "操作日志",
  "Operation": "操作",
  "Number of pens": "笔数",
  "Total amount of money": "总出款金额",
  "Already out of money": "已出款",
  "AutomaticAudit": "自动稽核",
  "WebsiteManagement": "网站资讯管理",
  "SiteDataEditor": "站点资料编辑",
  "GraphicEditor": "图文编辑",
  "CopyEditor": "文案编辑",
  "CaseEditor": "案件编辑",
  "ThePendingCase": "待审案件",
  "InThePendingCase": "待审中案件",
  "ThroughCase": "通过案件",
  "QuashCase": "撤销案件",
  "Membership details": "会员详情",
  "describe": "描述",
  "Join condition": "加入条件",
  "membership": "会员人数",
  "Self service return water": "自助返水",
  "The defection of state": "反水状态",
  "Return water": "返水",
  "Membership time": "会员加入时间",
  "Join time": "加入时间",
  "Deposit times": "存款次数",
  "Total deposits": "存款总额",
  "Max deposits": "最大存款",
  "Withdrawals times": "提款次数",
  "Withdrawals Total": "提款总额",
  "Max Withdrawals": "最大提款",
  "Profit": "盈利",
  "Member hierarchy": "会员分层",
  "Layered": "分层",
  "regression": "回归",
  "Payment settings": "支付设置",
  "Verify that the user is moved to non - hierarchical ?": "确认要将该用户移到未分层?",
  "Hierarchical": "层级",
  "Batch mode": "批量方式",
  "Min value": "最小值",
  "Max value": "最大值",
  "Query criteria": "查询条件",
  "Auto refresh": "自动刷新",
  "Hierarchical query": "层级查询",
  "Shareholder": "所属股东",
  "General agent": "所属总代理",
  "agent": "所属代理商",
  "General Agent": "总代理",
  "Agent": "代理商",
  "Fuzzy query": "模糊查询",
  "Serial number": "序号",
  "Electronic name": "电子名称",
  "Navigation background color": "导航背景颜色",
  "Navigate selected color": "导航选中颜色",
  "Button background color": "按钮背景颜色",
  "Button to select the color": "按钮选中颜色",
  "Button border color": "按钮边框颜色",
  "Entering the template sorting of the lottery Hall": "进入彩票大厅模版排序",
  "Lottery name": "彩票名称",
  "Lottery Hall": "彩票大厅",
  "Source selection": "来源选择",
  "Reset sort": "重置排序",
  "WAP icon Preview": "WAP图标预览",
  "Preview": "预览",
  "Restore the old version": "还原老版本",
  "Video name": "视讯名称",
  "WebSite name": "网站名称",
  "Width 90px height 65px": "宽度90px高度65px",
  "Registration settings": "注册设定",
  "Nickname Chinese": "中文昵称",
  "Promotion URL": "推广网址",
  "function": "功能",
  "New account": "新增账号",
  "Detailed content": "详情内容",
  "New proxy account": "新增代理账号",
  "Proxy name": "代理名称",
  "Proxy information": "代理资料",
  "Proxy account": "代理账号",
  "Please enter a query account": "请输入查询账号",
  "Real name": "真实姓名",
  "Full name": "姓名",
  "English name": "英语名称",
  "ID number": "身份证号码",
  "Withdrawal bank": "取款银行",
  "Bank account": "银行账号",
  "Province": "省份",
  "Counties and cities": "县市",
  "ATM password": "取款密码",
  "Other promotion methods": "其他推广方式",
  "Enable Member registration": "是否启用会员注册",
  "Picture path": "图片路径",
  "Advertising remarks": "广告备注",
  "yes": "是",
  "No": "否",
  "Preferential standards": "优惠标准",
  "Preferential percentage": "优惠百分比",
  "Single maximum deposit": "单次最高存款金额",
  "Single minimum deposit": "单次最低存款金额",
  "Preferential online amount": "优惠上线金额",
  "Other preferential standards": "其他优惠标准",
  "0 is no upper limit": "0为不设上限",
  "Comprehensive audit": "综合额度稽核",
  "Percentage of other deposit preferences": "其他存款优惠百分比",
  "Online and other preferential income limit": "线上入款其他優惠上限",
  "The upper limit of the other 24 hours": "其他24小时内最高上限",
  "The date of birth is the indication of whether or not it is hidden": "出生日期【是表示显示，否表示隐藏】",
  "The introducer is said to show, not to hide": "介绍人【是表示显示，否表示隐藏】",
  "The promoters name is show no means hide": "推广人姓名【是表示显示，否表示隐藏】",
  "Name repetition means permission to repeat": "姓名重复【是表示允许重复】",
  "Password authentication settings": "口令验证设置",
  "On-line": "在线",
  "Off-line": "离线",
  "whole": "全部",
  "Line": "线下",
  "Minimum effective purchase": "最低有效购买",
  "Preferential upper limit": "优惠上限",
  "Upper limit": "上限",
  "Last logon time": "最后登录时间",
  "Finally login to IP": "最后登录IP",
  "Login time": "登陆次数",
  "Registered IP": "注册IP",
  "Popularize ID": "推广ID",
  "Please enter the promotion ID": "请输入推广ID",
  "Please enter the registration IP": "请输入注册IP",
  "New date": "新增日期",
  "Date": "日期",
  "Landing error times": "登录错误次数",
  "current state": "当前状态",
  "suspend": "暂停",
  "Operation password": "操作密码",
  "Do you need a password": "是否需要密码",
  "Do you want to enable dynamic password settings": "是否启用动态口令设置",
  "secret key": "密钥",
  "Promote domain names": "代理推广域名",
  "Popularizing ID": "推广ID",
  "Login account": "登录账号",
  "Membership": "会员数",
  "Sports accounted for": "体育占成",
  "Video accounting": "视讯占成",
  "condition": "状况",
  "Recommended number of members": "推荐会员数",
  "Maid profit": "返佣获利",
  "Date query": "日期查询",
  "Set up": "设定",
  "data": "资料",
  "Discount": "优惠活动",
  "Domain extension": "推广域名",
  "General agent name": "总代理名称",
  "General agent account number": "总代理账号",
  "Lottery accounts for": "彩票占成",
  "Modify the general agent account": "修改总代理账号",
  "Member registration privilege setting": "旗下会员注册优惠设定",
  "Apply for membership registration privilege": "申请会员注册优惠",
  "Discount code": "优惠打码",
  "times": "倍",
  "Limit IP": "限制IP",
  "Normalization audit lending": "常态性稽核放款额度",
  "Normal audit administrative rate": "常态性稽核行政费率",
  "Clear lower level settings": "是否清除下级设定",
  "Shareholder account": "股东账号",
  "Hierarchy selection": "层级选择",
  "Choice of banks": "选择银行",
  "Hidden": "是否隐藏",
  "source": "来源",
  "Registration date": "注册日期",
  "sort": "排序",
  "System quota": "系统额度",
  "Video balance": "视讯额度",
  "Kick line": "踢线",
  "Bet": "下注",
  "cash": "现金",
  "To update": "更新",
  "Modify member account": "修改会员账号",
  "Can I change the password": "是否可修改密码",
  "Do you need a mailbox for registration": "注册是否需要邮箱",
  "Does registration require WeChat": "注册是否需要微信",
  "Does registration require documentation": "注册是否需要证件",
  "Do you need a telephone for registration": "注册是否需要电话",
  "Does registration require birthdays": "注册是否需要生日",
  "enable Member registration": "是否启用会员注册",
  "Do you need real names": "是否需要真实姓名",
  "Whether to display the introducer": "是否显示介绍人",
  "Do you need to fill in the bank card number": "注册是否需要填写银行卡号",
  "Can the phone be repeated": "电话是否可以重复",
  "Can the mailbox be repeated": "邮箱是否可以重复",
  "Can QQ repeat": "QQ是否可以重复",
  "Can WeChat repeat it": "微信是否可以重复",
  "Do you want to open the authentication code": "是否开启验证码",
  "Membership application amount": "会员申请优惠金额",
  "Code": "打码",
  "Do you want to limit IP": "是否限制IP",
  "Does registration require QQ": "注册是否需要QQ",
  "Self profit": "自身盈利",
  "Year and month selection": "年月选择",
  "Year": "年",
  "Month": "月",
  "Event": "事件",
  "Number of people": "人数",
  "Creation date": "创建日期",
  "Return water interval starting": "返水区间(起)",
  "Return water interval stop": "返水区间(止)",
  "Do not cross month inquiry": "请勿跨月查询",
  "Comprehensive code multiplier": "综合打码倍数",
  "Inquire detail": "查询明细",
  "System selection": "体系选择",
  "Membership level": "会员层级",
  "Non return water": "未返水",
  "Creator": "创建者",
  "Home return range starting": "返佣区间(起)",
  "Home return range stop": "返佣区间(止)",
  "Selection of the year": "年月份选择",
  "Number coefficient of the list": "排行榜人数系数",
  "Rankings coefficient": "排行金额系数",
  "Does a member of a maid need to make a code": "返佣会员是否需要打码",
  "Does it match the extension of the membership agent": "是否匹配推广会员代理",
  "Tip3": "多个QQ中间用','隔开",
  "Tip4": "多个微信中间用','隔开",
  "Tip5": "多个邮箱中间用','隔开",
  "Tip6": "多个电话中间用','隔开",
  "Tip7": "必须包含http://或https://",
  "Tip8": "如不开启层级返点优惠分区，选择默认选择",
  "Tip9": "如果注册会员IP与推广会员相同,此会员属于无效推广会员",
  "Tip10": "注册会员的代理使用推广会员的代理ID",
  "Tip11": "返佣会员没有打码则返佣数据为0",
  "Tip12": "虚拟数据系数,建议初始值0.2,每周增幅0.1",
  "Tip13": "虚拟金额系数",
  "Tip14": "如不开启层级返点优惠分区，选择默认选择",
  "Customer service WeChat": "客服微信",
  "Need": "需要",
  "Unwanted": "不需要",
  "Sure": "可以",
  "May not": "不可以",
  "Required": "必填",
  "Customer service QQ": "客服QQ",
  "application time": "申请时间",
  "Do you want to enable proxy registration settings": "是否启用代理注册设定",
  "Do you have a Chinese nickname": "是否中文昵称",
  "Do you have a English nickname": "是否英文昵称",
  "Do you need ID number": "是否需要证件号",
  "Do you need a mailbox": "是否需要邮箱",
  "Do you need QQ": "是否需要QQ",
  "Do you need phone number": "是否需要电话号",
  "Do you need to promote the URL": "是否需要推广网址",
  "Do you need any other methods": "是否需要其他方法",
  "Chinese nickname is required": "中文昵称是否必填",
  "English nickname is required": "英文昵称是否必填",
  "Whether the mailbox is required": "邮箱是否必填",
  "Documents are required": "证件是否必填",
  "QQ is required": "QQ是否必填",
  "Mobile phone number is required": "手机号是否必填",
  "The URL is required for promotion": "推广网址是否必填",
  "The other way is required": "其他方式是否必填",
  "Proxy registration settings": "代理注册设定",
  "Query date": "查询日期",
  "Change date": "更改日期",
  "Deposit date interval": "存款日期区间",
  "Date of deposit": "存款日期",
  "Payment procedure": "出款手续费",
  "Whether or not to exempt from formalities": "是否免手续费",
  "Exemption fee": "免手续费",
  "Unavoidable formalities": "不免手续费",
  "Free fee times": "免手续费次数",
  "Amount of payment": "出款手续费金额",
  "Entry and exit setting": "出入款设定",
  "Online deposit": "线上存款",
  "Every time": "每次",
  "Can give online preferential deposit deposit": "可放弃线上入款存款优惠",
  "Single line down line": "单次额度转下线",
  "Actual purchase": "实际购买",
  "Preferential audit": "优惠稽核",
  "Normal audit": "常态稽核",
  "Total consumption": "总消费",
  "Return level": "返点层级",
  "Total effective betting": "总有效投注",
  "Effective betting": "有效投注",
  "New preference setting": "新增优惠设定",
  "Total effectiveness": "总有效",
  "So video effective injection": "所以视讯有效投注",
  "Since the first deposit started after the payment": "自从出款后第一次存款开始之后",
  "ExitManagement": "出入款管理",
  "ArtificialWithdrawal": "人工取款",
  "AuditManagement": "稽核管理",
  "PlatformManagement": "管理员",
  "CommodityManagement": "商品管理",
  "PlatformAccount": "平台管理",
  "AccountManagement": "开户人管理",
  "RoleManagement": "角色管理",
  "MenuManagement": "菜单管理",
  "FunctionManagement": "权限管理",
  "PackageManagement": "套餐管理",
  "WebsiteInformation": "网站信息",
  "videoManagement": "视讯管理",
  "electronicManagement": "电子管理",
  "sportManagement": "体育管理",
  "lotteryManagrment": "彩票管理",
  "modularManagement": "模块管理",
  "PreferencesSettings": "自助申请优惠设置",
  "cacheManagement": "缓存管理",
  "LogoManagement": "LOGO管理",
  "FloatImg": "浮动图片",
  "SwiperImg": "轮播图片",
  "Notice": "公告弹框",
  "Advertisement": "广告管理",
  "GamePic": "首页游戏图",
  "Upload": "附件上传",
  "LOGO name": "LOGO名称",
  "Attachment": "附件管理",
  "Tip1": "提示：为防止页面排版样式冲突，请您尽量上传图片",
  "Appendix headlines": "附件标题",
  "Appendix address": "附件地址",
  "Upload a picture": "上传图片",
  "Address": "地址",
  "Upload time": "上传时间",
  "HomeCopy": "首页文案",
  "DepositCopy": "存款文案",
  "RegisterCopy": "注册文案",
  "WapDiscount": "WAP优惠活动",
  "LineDetection": "线路检测",
  "NewApplication": "银行卡设定",
  "screening": "筛选",
  "Platformaccount": "平台管理列表",
  "Functionmanagement": "功能管理",
  "Typemanagement": "类型管理",
  "configuration": "配置管理",
  "Layout Options": "布局选项",
  "Fixed Header": "固定头",
  "Fixed Navigation": "固定导航",
  "Fixed Ribbon": "固定带",
  "Fixed Footer": "固定页脚",
  "Inside": "容器",
  "container": "内",
  "RTL": "RTL",
  "Menu on top": "菜单上",
  "For Colorblind": "对于色盲",
  "experimental": "实验",
  "Clear Local storage": "清除本地存储",
  "Factory Reset": "恢复出厂设置",
  "Smart Admin Skins": "智能管理皮肤",
  "Smart Default": "智能默认",
  "Dark Elegance": "黑暗的优雅",
  "Ultra Light": "超轻",
  "Google Skin": "谷歌的皮肤",
  "Pixel Smash": "像素粉碎",
  "Glass": "玻璃",
  "Material Design beta": "材料设计测试",
  "success": "操作成功",
  "confirmationOperation": "是否确认此操作",
  "confirmStorage": "确定存储",
  "Storage case": "存储案件",
  "confirmEnable": "确定启用",
  "confirmDisable": "确定禁用",
  "Determine": "确定",
  "birthdays": "出生日期",
  "rmdRequired": "RMB表示人民币，必选",
  "hierarchyName": "层级名称",
  "number": "编号",
  "Transfer in amount": "转入金额",
  "Transfer in date": "转入日期",
  "Third party quota recharge": "第三方额度充值",
  "Bank card amount recharge": "银行卡额度充值",
  "fixedNumber": "固定编号（最多4位）",
  "requiredSpecialCharacters": "必填，请勿使用特殊字符",
  "default0,isUnrestricted": "默认0为整数，0表示无限制",
  "Tip2": "自助申请优惠乃付费功能，需付款才可开通",
  "Adding self-help applications": "添加自助申请优惠活动",
  "Return": "返回",
  "Module name": "模块名称",
  "Recharge list": "充值列表",
  "Recharge amount": "充值金额",
  "Payment bank": "支付银行",
  "The Bank": "银行",
  "Opening bank": "开户行",
  "Payee": "收款人",
  "Discontinued amount": "停用金额",
  "Application level": "适用层级",
  "Layered ID": "分层id",
  "Layered name": "分层名称",
  "Type of Bank": "银行类型",
  "Payment account": "支付账号",
  "Receivables bank": "收款银行",
  "Video type": "视讯类型",
  "addDomain": "添加域名",
  "Please enter the account number": "请输入账号",
  "Transaction other": "交易别",
  "Type of transaction": "交易类型",
  "Proportionate": "抽成比例",
  "Turn out the number of pens": "转出笔数",
  "Turn in the number of pens": "转入笔数",
  "State of payment": "支付状态",
  "Payment type": "支付类型",
  "Result": "结果",
  "Pen": "笔",
  "Video transfer line": "视讯转出额度",
  "Video transfer to the amount": "视讯转入额度",
  "An increase in the purse": "钱包增加额度",
  "Purse deductions": "钱包扣除额度",
  "Purse balance": "钱包余额",
  "modifyDomain": "修改域名",
  "addPromoteDomain": "添加代理推广域名",
  "englishName": "英文名称",
  "agentModification": "代理管理资料修改",
  "area": "区",
  "cardNum": "银行卡号",
  "The amount is not allowed to be 0": "金额不允许为0",
  "Payment of domain names": "支付域名",
  "agency": "代理",
  "Unpaid": "未支付",
  "Payment method": "支付方式",
  "accountLength": "数字字母（a-z）长度（4-12位）",
  "digitalLetter": "账号长度5-12位，只能字母和数字组合",
  "modifyUserBank": "修改会员银行",
  "bankBranch": "支行名称",
  "card": "卡号",
  "passwordDigitalLetter": "密码长度6-12位，只能字母和数字组合",
  "agentDigitalLetter": "总代理长度6-12位，只能字母和数字组合",
  "modifyChildren": "修改子账号",
  "maximumOnline": "在线存提款最大金额",
  "maximumArtificial": "人工存提款最大金额",
  "bindingLoginIP": "绑定登录IP",
  "passwordkey": "口令密钥",
  "paymentPlatform": "支付平台设定",
  "fixedNumberComposed": "固定编号由4位字母加数字组成，首字母位大写",
  "hierarchyModify": "修改层级",
  "tryGift": "试玩赠送额度",
  "trialRegistration": "试玩注册是否开启",
  "wapRegistration": "wap注册是否单页面",
  "modifyShareholder": "修改股东账号",
  "noSale": "为0时加入会员不赠送优惠",
  "Selective stratification": "选择分层",
  "bulkDeposit": "批量存款",
  "prepareMoney": "预备出款",
  "confirMation": "确认出款",
  "refuse": "拒绝",
  "reason": "原因",
  "Use": "使用",
  "Not used": "未使用",
  "confirmReceipt": "确认入款",
  "monitor": "监控",
  "rebateKeep": "退佣存档",
  "retreats": "退佣冲销",
  "addPeriods": "新增期数",
  "modifyPeriods": "修改期数",
  "layeredDetails": "分层详情",
  "depositRecord": "存款记录",
  "selfSetting": "公司自定设置",
  "rmbSet": "币别设定",
  "currency": "币别",
  "Tokens": "代币",
  "Choose the coin": "选择币别",
  "setting": "设定",
  "Newly added": "新增",
  "newSetting": "新增设定",
  "Term name": "期数名称",
  "Query interval limit for two months": "查询区间限制两个月",
  "modifySetting": "修改设定",
  "detailed": "明细",
  "returnDetail": "返水明细",
  "modifyAnnouncement": "修改公告",
  "sendAudit": "发送审核",
  "choose": "选择",
  "modifyContent": "编辑内容",
  "templateChoose": "模板选择",
  "templateTitle": "模板选择",
  "templateContent": "模板内容",
  "keep": "储存案件",
  "update": "上传",
  "Rebate subtotal": "返点小计",
  "Total self-service return of water": "总自助返水",
  "Return time": "返水时间",
  "Returned water": "已返水",
  "Return water subtotal": "返水小计",
  "saleContent": "优惠内容",
  "Source of income": "入款来源",
  "preferential": "优惠",
  "themeConfigure": "电子内页主题配置",
  "Initialization": "初始化",
  "modifySort": "编辑顺序",
  "invalid": "置为无效",
  "membershipStatistics":"会员统计",
  "flowStatistics":"流量统计",
  "commodityStatistics":"商品统计",
  "transactionStatistics":"交易统计",
  "statistical":"统计管理",
  "SingleNote":"注单管理",
  "SportSingleNote":"体育注单",
  "LotterySingleNote":"彩票注单",
  "VideoSingleNote":"视讯注单",
  "GameSingleNote":"电子注单",
  "FishingSingleNote":"捕鱼注单"
}`
