package langs

var USLangsAdmin = `{
   "Projects": "Projects",
   "Msgs": "Msgs",
   "Notify": "Notify",
   "Tasks": "Tasks",
   "Recent projects": "Recent projects",
   "Find reports and more": "Find reports and more",
   "john.doe": "john.doe",
   "Dashboard": "Dashboard",
   "Angular Stuff": "Angular Stuff",
   "UI Bootstrap": "UI Bootstrap",
   "Get Locale JSON": "Get Locale JSON",
   "Inbox": "Inbox",
   "Graphs": "Graphs",
   "Flot Chart": "Flot Chart",
   "Morris Charts": "Morris Charts",
   "Inline Charts": "Inline Charts",
   "Dygraphs": "Dygraphs",
   "Tables": "Tables",
   "Normal Tables": "Normal Tables",
   "Data Tables": "Data Tables",
   "Forms": "Forms",
   "Smart Form Elements": "Smart Form Elements",
   "Smart Form Layouts": "Smart Form Layouts",
   "Smart Form Validation": "Smart Form Validation",
   "Bootstrap Form Elements": "Bootstrap Form Elements",
   "Form Plugins": "Form Plugins",
   "Wizards": "Wizards",
   "Bootstrap Editors": "Bootstrap Editors",
   "Dropzone": "Dropzone",
   "UI Elements": "UI Elements",
   "General Elements": "General Elements",
   "Buttons": "Buttons",
   "Icons": "Icons",
   "Font Awesome": "Font Awesome",
   "Glyph Icons": "Glyph Icons",
   "Grid": "Grid",
   "Tree View": "Tree View",
   "Nestable Lists": "Nestable Lists",
   "JQuery UI": "JQuery UI",
   "Typography": "Typography",
   "Six Level Menu": "Six Level Menu",
   "Item #2": "Item #2",
   "Sub #2.1": "Sub #2.1",
   "Item #2.1.1": "Item #2.1.1",
   "Expand": "Expand",
   "File": "File",
   "Delete": "Delete",
   "Item #3": "Item #3",
   "3rd Level": "3rd Level",
   "Calendar": "Calendar",
   "Widgets": "Widgets",
   "Gallery": "Gallery",
   "GMap Skins": "GMap Skins",
   "Miscellaneous": "Miscellaneous",
   "Other Pages": "Other Pages",
   "Forum Layout": "Forum Layout",
   "Profile": "Profile",
   "Timeline": "Timeline",
   "Pricing Tables": "Pricing Tables",
   "Invoice": "Invoice",
   "Login": "Login",
   "Register": "Register",
   "Locked Screen": "Locked Screen",
   "Error 404": "Error 404",
   "Error 500": "Error 500",
   "Blank Page": "Blank Page",
   "Email Template": "Email Template",
   "Search Page": "Search Page",
   "CK Editor": "CK Editor",
   "SmartAdmin Intel": "SmartAdmin Intel",
   "Different Versions": "Different Versions",
   "Documentation": "Documentation",
   "Bug Tracker": "Bug Tracker",
   "Mail": "Mail",
   "Maps": "Maps",
   "My Profile": "My Profile",
   "Page Header": "Page Header",
   "Subtitle": "Subtitle",
   "Permission Grouping": "Permission Grouping",
   "Admin Account": "Admin Account",
   "Admin Log": "Admin Log",
   "Dealer Management": "Dealer Management",
   "Commodity": "Commodity",
   "Sort Management": "Sort Management",
   "Release goods": "Release goods",
   "Site": "Site",
   "Site List": "Site List",
   "Create Site": "Create Site",
   "Order Management": "Order Management",
   "Settlement": "Settlement",
   "Pending application": "Pending application",
   "Settlement record": "Settlement record",
   "Payment Management": "Payment Management",
   "Customer Management": "Customer Management",
   "Search": "Search",
   "AddMore": "AddMore",
   "GroupName": "GroupName",
   "Administrator Management": "Administrator",
   "Administrator Number": "Administrator",
   "Status": "Status",
   "Remarks": "Remarks",
   "Management": "Management",
   "PreviousPage": "Previous page",
   "NextPage": "Next page",
   "Edit": "Edit",
   "Order List": "Order List",
   "Payment channel": "Payment channel",
   "State": "State",
   "Please enter the name of the commodity": "Please enter the name of the commodity",
   "Commodity name": "Commodity name",
   "Unit price / quantity": "Unit price / quantity",
   "Owned dealer": "Owned dealer",
   "Customer nickname": "Customer nickname",
   "Classification of goods": "Classification of goods",
   "Order status": "Order status",
   "General Commission": "General Commission",
   "Bootstrap Form Validation": "Bootstrap Form Validation",
   "Outlook": "Outlook",
   "Cool Features": "Cool Features",
   "App Views": "App Views",
   "E-Commerce": "E-Commerce",
   "Home": "Home",
   "Settlement management": "Settlement management",
   "Settlement request": "Settlement request",
   "List of settlement requests": "List of settlement requests",
   "Start time of order creation": "Start time of order creation",
   "Order creation end time": "Order creation end time",
   "Dealer name search": "Dealer name search",
   "Order ID": "Order ID",
   "Dealer name": "Dealer name",
   "Application time": "Application time",
   "Balance of settlement": "Balance of settlement",
   "Settlement amount": "Settlement amount",
   "Administration": "Administration",
   "Payment interface management": "Payment interface management",
   "Payment interface list": "Payment interface list",
   "Add interface": "Add interface",
   "Service provider logo": "Service provider logo",
   "Interface name": "Interface name",
   "ID": "ID",
   "Flow amount": "Flow amount",
   "operation": "operation",
   "List of customer management": "List of customer management",
   "Customer source": "Customer source",
   "Customer ID": "Customer ID",
   "Subordinate site": "Subordinate site",
   "A turnover": "A turnover",
   "integral": "integral",
   "Administrator account": "Administrator account",
   "Select group name": "Select group name",
   "Administrator account search": "Administrator account search",
   "Accounts": "Accounts",
   "Creation Time": "Creation Time",
   "Dealer ID": "Dealer ID",
   "Total goods": "Total goods",
   "Total customer": "Total customer",
   "Total order": "Total order",
   "Total transaction": "Total transaction",
   "Total distribution": "Total distribution",
   "Distributor order totals": "Distributor order totals",
   "Distributor transaction volume": "Distributor transaction volume",
   "Total settlement": "Total settlement",
   "Registration time": "Registration time",
   "Settlement amount to be processed": "Settlement amount to be processed",
   "Site management": "Site management",
   "Choose dealers": "Choose dealers",
   "site": "Site",
   "ChildAccount": "Child Account",
   "MemberManagement": "Member Management",
   "FundManagement": "Fund Management",
   "MarginManagement": "Margin Management",
   "ReCommisManagement": "ReCommis Management",
   "RebateManagement": "RebateManagement",
   "Announcement": "Announcement",
   "SiteChoice": "SiteChoice",
   "UserName": "UserName",
   "DividedManagement": "Divided Management",
   "DealerQuantity": "Dealer Quantity",
   "DivideInto": "DivideInto",
   "CreatePacket": "Create Packet",
   "SortType": "SortType",
   "Enable": "Enable",
   "DealerCommission": "Dealer Commission",
   "DistributorRegistration": "Distributor Registration",
   "Dealer grouping": "Dealer grouping",
   "AdministratorGrouping": "Administrator Grouping",
   "addDelaer": "addDelaer",
   "DistributorName": "Distributor Name",
   "OrderDetails": "Order Details",
   "Check all": "Check all",
   "Batch pass": "Batch pass",
   "Level": "Level",
   "Name": "Name",
   "Balance": "Balance",
   "Reasons for rejection": "Reasons for rejection",
   "Member source": "Member source",
   "distributor": "distributor",
   "Online search": "Online search",
   "Member account": "Member account",
   "Distributors": "Distributors",
   "System balance": "System balance",
   "Online": "Online",
   "Member registration settings": "Member registration settings",
   "members registered": " members registered",
   "Tourist registration": "Tourist registration",
   "Registration requires mailbox": "Registration requires mailbox",
   "Are mailbox repeats allowed": "Are mailbox repeats allowed",
   "Registration requires QQ": "Registration requires QQ",
   "Are you allowed to repeat QQ": "Are you allowed to repeat QQ",
   "Registration requires phone": "Registration requires phone",
   "Are you allowed to repeat phone": "Are you allowed to repeat phone",
   "Registration requires birth date": "Registration requires birth date",
   "Open authentication code": "Open authentication code",
   "Done": "Done",
   "Member order list": "Member order list",
   "Commodity type": "Commodity type",
   "Settlement method": "Settlement method",
   "Order number": "Order number",
   "Order time": "Order time",
   "Transaction amount": "Transaction amount",
   "Purchase amount": "Purchase amount",
   "Add packet": "Add packet",
   "Packet information": "Packet information",
   "Privilege management": "Privilege management",
   "Functional module2": "Functional module2",
   "Function selection": "Function selection",
   "Module enabled": "Module enabled",
   "Create packet completion": "Create packet completion, add administrators to newly created packets in the admin module2, and manage permissions for groups in privilege management.",
   "Create success": "Create success",
   "See": "See",
   "Return list": "Return list",
   "Previous step": "Previous step",
   "Next step": "Next step",
   "Create schedule": "Create schedule",
   "Add Account": "Add Account",
   "accounts": "accounts",
   "Password": "Password",
   "Permission grouping": "Permission grouping",
   "Status enabled disabled": "Status enabled disabled",
   "Enables": "Enable",
   "Disable": "Disable",
   "Confirm": "Confirm",
   "Cancel": "Cancel",
   "Journal": "Journal",
   "Time": "Time",
   "Operation record": "Operation record",
   "Edit account": "Edit account",
   "Submit successfully": "Submit successfully",
   "View grouping": "View grouping",
   "Power": "Power",
   "Total administrator": "Total administrator",
   "Member list": "Member list",
   "Operating time": "Operating time",
   "Grounping": "Grounping",
   "Permission view": "Permission view",
   "Basic information": "Basic information",
   "Confirm password": "Confirm password",
   "Please enter your password again": "Please enter your password again",
   "Divide into groups": "Divide into groups",
   "Modify dealer": "Modify dealer",
   "Confirm submission": "Confirm submission",
   "Modified grouping": "Modified grouping",
   "Enable proxy registration": "Enable proxy registration",
   "Primary dealer": "Primary dealer",
   "Two dealer": "Two dealer",
   "Please enter": "Please enter ",
   "Distributor quantity": "Distributor quantity",
   "Distributor split ratio setting": "Distributor split ratio setting",
   "My ratio": "My ratio",
   "Subordinate ratio": "Subordinate ratio",
   "Packet creation": "Packet creation",
   "Modify": "Modify",
   "Please enter the name of the applicant": "Please enter the name of the applicant",
   "Applicant ID": "Applicant ID",
   "Applicant name": "Applicant name",
   "Subordinate": "Subordinate",
   "CAAC Certificate No": "CAAC Certificate No",
   "Mailbox": "Mailbox",
   "QQ": "QQ",
   "Cell-phone number": "Cell-phone number",
   "Child account list": "Child account list",
   "Unit price": "Unit price",
   "Number of shelves": "Number of shelves",
   "Commission amount": "Commission amount",
   "Inventory quantity": "Inventory quantity",
   "Batch shelves": "Batch shelves",
   "Details": "Details URL",
   "Are goods allowed on shelves": "Are goods allowed on shelves",
   "Release": "Release",
   "(unit: yuan)": "(unit: yuan)",
   "Chinese: apples": "Chinese: apples",
   "(unit: Unit)": "(unit: Unit)",
   "Class A": "Class A",
   "Second level": "Second level",
   "Three": "Three",
   "Commodity details page": "Commodity details page",
   "View details of the goods": "View details of the goods",
   "View commodity information": "View commodity information",
   "Commodity attribute": "Commodity attribute",
   "Publication quantity": "Publication quantity",
   "View categories": "View categories",
   "Classified ID": "Classified ID",
   "Category name": "Category name",
   "Classification description": "Classification description",
   "Add categories": "Add categories",
   "Modify goods": "Modify goods",
   "Site name": "Site name",
   "Site information": "Site information",
   "Tip": "Tip",
   "Select site status": "Select site status",
   "Select the dealer or manually enter the dealer name": "Select the dealer or manually enter the dealer name",
   "PC domain name": "PC domain name",
   "Please enter the PC domain name": "Please enter the PC domain name",
   "WAP domain name": "WAP domain name",
   "Please enter the WAP domain name": "Please enter the WAP domain name",
   "SSI certificate": "SSI certificate",
   "Select file": "Select file",
   "Click Add domain name and certificate customer service information": "Click Add domain name and certificate customer service information",
   "WeChat": "WeChat",
   "Telephone": "Telephone",
   "Email": "Email",
   "Customer service information": "Customer service information",
   "Modify site information": "Modify site information",
   "EditAccount": "Edit Account",
   "EditGroup": "Edit Group",
   "MarginApplication": "Margin application",
   "Order information": "Order information",
   "Commodity information": "Commodity information",
   "Single product discount": "Single product discount",
   "Quantity purchased": "Quantity purchased",
   "Buy discount": "Buy discount",
   "Purchase amount1": "Purchase amount",
   "Operation type": "Operation type",
   "Deposit amount": "Deposit amount",
   "Deposit preferences": "Deposit preferences",
   "Access money": "Access money",
   "Sort": "Sort",
   "Deposit / withdrawal amount": "Deposit / withdrawal amount",
   "Member name": "Member name",
   "Commission list": "Commission list",
   "Commission setting": "Commission setting",
   "Parent account": "Parent account",
   "Recommended number": "Recommended number",
   "Rebate list": "Rebate list",
   "Margin application": "Margin application",
   "Please enter a single number": "Please enter a single number",
   "New application": "New application",
   "Apply for an account": "Apply for an account",
   "Application amount": "Application amount",
   "Date of application": "Date of application",
   "Remittance mode": "Remittance mode",
   "Report details": "Report details",
   "Export EXCEL": "Export EXCEL",
   "User information": "User information",
   "Recharge warning": "Recharge warning",
   "Recharge application": "Recharge application",
   "Recharge alert settings": "Recharge alert settings",
   "Debit note number": "Debit note number",
   "Deductible amount": "Deductible amount",
   "Date of deduction": "Date of deduction",
   "Associated single number": "Associated single number",
   "Third party payment": "Third party payment",
   "Bank card transfer": "Bank card transfer",
   "Bank remittance": "Bank remittance",
   "Remittance form": "Remittance form",
   "Platform name": "Platform ",
   "Girokonto": "Girokonto",
   "Collection account": "Collection account",
   "Transfer amount": "Transfer amount",
   "Transfer time": "Transfer time",
   "Bank name": "Bank name",
   "Transfer card number": "Transfer card number",
   "Collection card number": "Collection card number",
   "Running odd numbers": "Running odd numbers",
   "Rebate amount": "The rebate amount",
   "Set point": "Set point",
   "Check rebate": "Check the rebate",
   "Report form": "Report form",
   "End time": "End time",
   "Today": "Today",
   "Yesterday": "Yesterday",
   "Last week": "Last week",
   "This period": "This period",
   "Number and period in 2016": "Number and period in 2016",
   "Number and period in 2017": "Number and period in 2017",
   "Report type": "Report type",
   "New announcement": "New announcement",
   "Title": "Title",
   "Content": "Content",
   "Release time": "Release time",
   "Publish account": "Publish account",
   "VType": "VType",
   "Dealer account": "Dealer account",
   "Announcement type": "Announcement type",
   "Please select": "Please select",
   "Announcement heading": "Announcement heading",
   "Announcement content": "Announcement content",
   "Subordinate group": "Subordinate group",
   "Recording time": "Recording time",
   "IP address": "IP address",
   "Operation behavior": "Operation behavior",
   "Administrator operation": "Administrator operation",
   "Grade": "Grade",
   "SettlementRequest": "SettlementRequest",
   "DistributorBalance": "DistributorBalance",
   "Account management": "Account management",
   "Distributor list": "Distributor list",
   "Distributor Application List": "Distributor Application List",
   "Distributor application setting": "Distributor application setting",
   "Transaction management": "Transaction management",
   "Goods shelves (dealers)": "Goods shelves (dealers) ",
   "List of goods on shelves": "List of goods on shelves",
   "Rebate settings": "Rebate settings",
   "SystemSettings": "System settings",
   "Member registration management": "Member registration management",
   "Member grouping management": "Member grouping management",
   "Distributor balance view": "Distributor balance view",
   "ReportForm": "ReportForm",
   "A_1": "Member",
   "A_2": "Shareholder",
   "A_3": "General Agent",
   "A_4": "Agent",
   "A_5": "Child Account",
   "A_6": "Member Registration",
   "A_7": "Agency Application",
   "A_8": "System Query",
   "A_9": "Hierarchical",
   "DepositsWithdrawals": "Deposits and withdrawals",
   "HistoryQuery": "History Query",
   "QuotaConversion": "Quota Conversion",
   "MarginReplacement": "Margin replacement record",
   "entryAndExit": "Summary of entry and exit",
   "CashManagement": "Cash Management",
   "MoneyManagement": "Money Management",
   "companyInChina": "company In China",
   "ChinaOnline": "China Online",
   "Immediate": "Immediate audit query",
   "auditLog": "Audit Log",
   "PaymentSetting": "Payment Setting",
   "BankElimination": "Bank Elimination",
   "DepositBankSet": "Deposit Bank Set",
   "IncomeExcludingBank": "Income Excluding Bank",
   "bankElimination": "bank Elimination",
   "OnlinePaymentSetup": "Online Payment Setup",
   "PaymentParameterSetting": "Payment Parameter Setting",
   "AutomaticCashSetting": "Automatic Cash Setting",
   "CashSystem": "Cash System",
   "MemberAnalysis": "Member Analysis",
   "Analysis": "Analysis",
   "MemberInquiries": "Member Inquiries",
   "PurchaseAnalysis": "Purchase Analysis",
   "PreferentialAnalysis": "Preferential Analysis",
   "ValidMembershipList": "Valid MembershipList",
   "CommissionStatistics": "Commission Statistics",
   "AgentRetirementSetting": "Agent Retirement Setting",
   "PeriodManagement": "Period Management",
   "FeeSetting": "Fee Setting",
   "CommissionInquiry": "Commission Inquiry",
   "MemberBalance": "Member Balance",
   "PreferentialCalculation": "Preferential Calculation",
   "SetPreferential": "Set Preferential",
   "PreferentialInquiry": "Preferential Inquiry",
   "PreferentialStatistics": "Preferential Statistics",
   "SelfDefectionQuery": "Self Defection Query",
   "MembershipReturns": "Membership Returns",
   "CommissionSetting": "Commission Setting",
   "RebateSetting": "Rebate Setting",
   "MemberPromotionInquiries": "Member Promotion Inquiries",
   "MemberPromotionSettings": "Member Promotion Settings",
   "QuotaStatistics": "Quota Statistics",
   "RechargeRecord": "Recharge Record",
   "DropList": "Drop List",
   "QuotaRecharge": "Quota Recharge",
   "QuotaRecord": "Quota Record",
   "AnnouncementInformation": "Announcement Information",
   "SystemAnnouncement": "System Announcement",
   "MemberMessage": "Member Message",
   "ReleaseNewMessages": "Release New Messages",
   "RegistrationCouponTemplates": "Registration Coupon Templates",
   "LatestNews": "Latest News",
   "LogManagement": "Log Management",
   "MemberLogin": "Member Login",
   "AdministratorLogin": "Administrator Login",
   "OperationLog": "Operation Log",
   "AutomaticAudit": "Automatic Audit",
   "WebsiteInformation": "Website Information",
   "SiteDataEditor": "Site Data Editor",
   "GraphicEditor": "Graphic Editor",
   "CopyEditor": "Copy Editor",
   "CaseEditor": "Copy Editor",
   "ThePendingCase": "The Pending Case",
   "InThePendingCase": "In The Pending Case",
   "ThroughCase": "Through Case",
   "QuashCase": "Quash Case",
   "Membership details": "Membership details",
   "describe": "describe",
   "Join condition": "Join condition",
   "membership": "membership",
   "Self service return water": "Self service return water",
   "Membership time": "Membership time",
   "Deposit times": "Deposit times",
   "Total deposits": "Total deposits",
   "Member hierarchy": "Member hierarchy",
   "Layered": "Layered",
   "regression": "regression",
   "Payment settings": "Payment settings",
   "Verify that the user is moved to non - hierarchical ?": "Verify that the user is moved to non - hierarchical ?",
   "Hierarchical query": "Hierarchical query",
   "Shareholder": "Shareholder",
   "General agent": "General agent",
   "agent": "agent",
   "Fuzzy query": "Fuzzy query",
   "Serial number": "Serial number",
   "Member": "Member",
   "Registration settings": "Registration settings",
   "Nickname Chinese": "Nickname Chinese",
   "Promotion URL": "Promotion URL",
   "function": "function",
   "New account": "New account",
   "Detailed content": "Detailed content",
   "New proxy account": "New proxy account",
   "Proxy name": "Proxy name",
   "Proxy information": "Proxy information",
   "Proxy account": "Proxy account",
   "Real name": "Real name",
   "English name": "English name",
   "ID number": "ID number",
   "Withdrawal bank": "Withdrawal bank",
   "Bank account": "Bank account",
   "Province": "Province",
   "Counties and cities": "Counties and cities",
   "ATM password": "ATM password",
   "Other promotion methods": "Other promotion methods",
   "Enable Member registration": "Enable Member registration",
   "yes": "yes",
   "No": "No",
   "The date of birth is the indication of whether or not it is hidden": "The date of birth is the indication of whether or not it is hidden",
   "The introducer is said to show, not to hide": "The introducer is said to show, not to hide",
   "The promoters name is show no means hide": "The promoter's name is show, no means hide",
   "Name repetition means permission to repeat": "Name repetition means permission to repeat",
   "Password authentication settings": "Password authentication settings",
   "On-line": "On-line",
   "whole": "whole",
   "Line": "Line",
   "Login account": "Login account",
   "Last logon time": "Last logon time",
   "Finally login to IP": "Finally login to IP",
   "New date": "New date",
   "Landing error times": "Landing error times",
   "current state": "current state",
   "suspend": "suspend",
   "Operation password": "Operation password",
   "Do you need a password": "Do you need a password",
   "Do you want to enable dynamic password settings": "Do you want to enable dynamic password settings",
   "secret key": "secret key",
   "Promote domain names": "Promote domain names",
   "Popularizing ID": "Popularizing ID",
   "Membership": "Membership",
   "Sports accounted for": "Sports accounted for",
   "Lottery accounts for": "Lottery accounts for",
   "Video accounting": "Video accounting",
   "status": "status",
   "Set up": "Set up",
   "data": "data",
   "Discount": "Discount",
   "Domain extension": "Domain extension",
   "General agent name": "General agent name",
   "General agent account number": "General agent account number",
   "Modify the general agent account": "Modify the general agent account",
   "Member registration privilege setting": "Member registration privilege setting",
   "Apply for membership registration privilege": "Apply for membership registration privilege",
   "Discount code": "Discount code",
   "times": "times",
   "Limit IP": "Limit IP",
   "Clear lower level settings": "Clear lower level settings",
   "Shareholder account": "Shareholder account",
   "A_1_1": "Official account",
   "Hidden": "Hidden",
   "source": "source",
   "Registration date": "Registration date",
   "sort": "sort",
   "System quota": "System quota",
   "Video balance": "Video balance",
   "Kick line": "Kick line",
   "Bet": "Bet",
   "cash": "cash",
   "To update": "To update",
   "A_1_2": "Play account",
   "Modify member account": "Modify member account",
   "Can I change the password": "Can I change the password",
   "A_1_3": "Add play",
   "Do you need a mailbox for registration": "Do you need a mailbox for registration",
   "Does registration require WeChat": "Does registration require WeChat",
   "Does registration require documentation": "Does registration require documentation",
   "Do you need a telephone for registration": "Do you need a telephone for registration",
   "Does registration require birthdays": "Does registration require birthdays",
   "enable Member registration": "Enable Member registration",
   "Do you need real names": "Do you need real names",
   "Whether to display the introducer": "Whether to display the introducer",
   "Do you need to fill in the bank card number": "Do you need to fill in the bank card number",
   "Can the phone be repeated": "Can the phone be repeated",
   "Can the mailbox be repeated": "Can the mailbox be repeated",
   "Can QQ repeat": "Can QQ repeat",
   "Can WeChat repeat it": "Can WeChat repeat it",
   "Do you want to open the authentication code": "Do you want to open the authentication code",
   "Membership application amount": "Membership application amount",
   "Code": "Code",
   "Do you want to limit IP": "Do you want to limit IP",
   "Does registration require QQ": "Does registration require QQ",
   "Need": "Need",
   "Unwanted": "Unwanted",
   "Sure": "Sure",
   "May not": "May not",
   "application time": "Application time",
   "Do you want to enable proxy registration settings": "Do you want to enable proxy registration settings",
   "Do you have a Chinese nickname": "Do you have a Chinese nickname",
   "Do you have a English nickname": "Do you have a English nickname",
   "Do you need ID number": "Do you need ID number",
   "Do you need a mailbox": "Do you need a mailbox",
   "Do you need QQ": "Do you need QQ",
   "Do you need phone number": "Do you need phone number",
   "Do you need to promote the URL": "Do you need to promote the URL",
   "Do you need any other methods": "Do you need any other methods",
   "Chinese nickname is required": "Chinese nickname is required",
   "English nickname is required": "English nickname is required",
   "Whether the mailbox is required": "Whether the mailbox is required",
   "Documents are required": "Documents are required",
   "QQ is required": "QQ is required",
   "Mobile phone number is required": "Mobile phone number is required",
   "The URL is required for promotion": "The URL is required for promotion",
   "The other way is required": "The other way is required",
   "Proxy registration settings": "Proxy registration settings",
   "ExitManagement": "ExitManagement",
   "ArtificialWithdrawal": "Artificial Withdrawal",
   "AuditManagement": "Audit Management",
   "PlatformManagement": "Platform Management",
   "CommodityManagement": "Commodity Management",
   "PlatformAccount": "Platform account management",
   "AccountManagement": "Account Management",
   "RoleManagement": "Role Management",
   "MenuManagement": "Menu Management",
   "FunctionManagement": "Function Management",
   "PackageManagement": "Package Management",
   "WebsiteManagement": "Website In for mation",
   "videoManagement": "Video Management",
   "electronicManagement": "Electronic Management",
   "sportManagement": "Sport Management",
   "lotteryManagrment": "Lottery Managrment",
   "modularManagement": "Modular Management",
   "PreferencesSettings": "Preferences Settings",
   "cacheManagement": "Cache Management",
   "LogoManagement": "Logo Management",
   "FloatImg": "Float Img",
   "SwiperImg": "Swiper Img",
   "Notice": "Notice",
   "Advertisement": "Advertisement",
   "GamePic": "GamePic",
   "Upload": "Upload",
   "Attachment": "Attachment",
   "HomeCopy": "Home Copy",
   "DepositCopy": "Deposit Copy",
   "RegisterCopy": "Register Copy",
   "WapDiscount": "WapDiscount",
   "LineDetection": "LineDetection",
   "NewApplication": "NewApplication",
   "screening": "screening",
   "Platformaccount": "Platformaccount",
   "A_10": "account Management",
   "Functionmanagement": "Functionmanagement",
   "Typemanagement": "Typemanagement",
   "configuration": "configuration",
   "Layout Options": "Layout Options",
   "Fixed Header": "Fixed Header",
   "Fixed Navigation": "Fixed Navigation",
   "Fixed Ribbon": "Fixed Ribbon",
   "Fixed Footer": "Fixed Footer",
   "Inside": "Inside",
   "container": "container",
   "RTL": "RTL",
   "Menu on top": "Menu on top",
   "For Colorblind": "For Colorblind",
   "experimental": "experimental",
   "Clear Local storage": "Clear Localstorage",
   "Factory Reset": "Factory Reset",
   "Smart Admin Skins": "Smart Admin Skins",
   "Smart Default": "Smart Default",
   "Dark Elegance": "Dark Elegance",
   "Ultra Light": "Ultra Light",
   "Google Skin": "Google Skin",
   "Pixel Smash": "PixelSmash",
   "Glass": "Glass",
   "Material Design beta": "Material Design beta",
   "success": "success",
   "confirmationOperation": "Whether this operation is confirmed",
   "Membership import": "Membership import"
}`

var USLangsAgency = `{
   "Projects": "Projects",
   "Msgs": "Msgs",
   "Notify": "Notify",
   "Tasks": "Tasks",
   "Recent projects": "Recent projects",
   "Find reports and more": "Find reports and more",
   "john.doe": "john.doe",
   "Dashboard": "Dashboard",
   "Angular Stuff": "Angular Stuff",
   "UI Bootstrap": "UI Bootstrap",
   "Get Locale JSON": "Get Locale JSON",
   "Inbox": "Inbox",
   "Graphs": "Graphs",
   "Flot Chart": "Flot Chart",
   "Morris Charts": "Morris Charts",
   "Inline Charts": "Inline Charts",
   "Dygraphs": "Dygraphs",
   "Tables": "Tables",
   "Normal Tables": "Normal Tables",
   "Data Tables": "Data Tables",
   "Forms": "Forms",
   "Smart Form Elements": "Smart Form Elements",
   "Smart Form Layouts": "Smart Form Layouts",
   "Smart Form Validation": "Smart Form Validation",
   "Bootstrap Form Elements": "Bootstrap Form Elements",
   "Form Plugins": "Form Plugins",
   "Wizards": "Wizards",
   "Bootstrap Editors": "Bootstrap Editors",
   "Dropzone": "Dropzone",
   "UI Elements": "UI Elements",
   "General Elements": "General Elements",
   "Buttons": "Buttons",
   "Icons": "Icons",
   "Font Awesome": "Font Awesome",
   "Glyph Icons": "Glyph Icons",
   "Grid": "Grid",
   "Tree View": "Tree View",
   "Nestable Lists": "Nestable Lists",
   "JQuery UI": "JQuery UI",
   "Typography": "Typography",
   "Six Level Menu": "Six Level Menu",
   "Item #2": "Item #2",
   "Sub #2.1": "Sub #2.1",
   "Item #2.1.1": "Item #2.1.1",
   "Expand": "Expand",
   "File": "File",
   "Delete": "Delete",
   "Item #3": "Item #3",
   "3rd Level": "3rd Level",
   "Calendar": "Calendar",
   "Widgets": "Widgets",
   "Gallery": "Gallery",
   "GMap Skins": "GMap Skins",
   "Miscellaneous": "Miscellaneous",
   "Other Pages": "Other Pages",
   "Forum Layout": "Forum Layout",
   "Profile": "Profile",
   "Timeline": "Timeline",
   "Pricing Tables": "Pricing Tables",
   "Invoice": "Invoice",
   "Login": "Login",
   "Register": "Register",
   "Locked Screen": "Locked Screen",
   "Error 404": "Error 404",
   "Error 500": "Error 500",
   "Blank Page": "Blank Page",
   "Email Template": "Email Template",
   "Search Page": "Search Page",
   "CK Editor": "CK Editor",
   "SmartAdmin Intel": "SmartAdmin Intel",
   "Different Versions": "Different Versions",
   "Documentation": "Documentation",
   "Bug Tracker": "Bug Tracker",
   "Mail": "Mail",
   "Maps": "Maps",
   "My Profile": "My Profile",
   "Page Header": "Page Header",
   "Subtitle": "Subtitle",
   "Permission Grouping": "Permission Grouping",
   "Admin Account": "Admin Account",
   "Admin Log": "Admin Log",
   "Dealer Management": "Dealer Management",
   "Commodity": "Commodity",
   "Sort Management": "Sort Management",
   "Release goods": "Release goods",
   "Site": "Site",
   "Site List": "Site List",
   "Create Site": "Create Site",
   "Order Management": "Order Management",
   "Settlement": "Settlement",
   "Pending application": "Pending application",
   "Settlement record": "Settlement record",
   "Payment Management": "Payment Management",
   "Customer Management": "Customer Management",
   "Search": "Search",
   "AddMore": "AddMore",
   "GroupName": "GroupName",
   "Administrator Management": "Administrator",
   "Administrator Number": "Administrator",
   "Status": "Status",
   "Remarks": "Remarks",
   "Management": "Management",
   "PreviousPage": "Previous page",
   "NextPage": "Next page",
   "Edit": "Edit",
   "Order List": "Order List",
   "Payment channel": "Payment channel",
   "State": "State",
   "Please enter the name of the commodity": "Please enter the name of the commodity",
   "Commodity name": "Commodity name",
   "Unit price / quantity": "Unit price / quantity",
   "Owned dealer": "Owned dealer",
   "Customer nickname": "Customer nickname",
   "Classification of goods": "Classification of goods",
   "Order status": "Order status",
   "General Commission": "General Commission",
   "Bootstrap Form Validation": "Bootstrap Form Validation",
   "Outlook": "Outlook",
   "Cool Features": "Cool Features",
   "App Views": "App Views",
   "E-Commerce": "E-Commerce",
   "Home": "Home",
   "Settlement management": "Settlement management",
   "Settlement request": "Settlement request",
   "List of settlement requests": "List of settlement requests",
   "Start time of order creation": "Start time of order creation",
   "Order creation end time": "Order creation end time",
   "Dealer name search": "Dealer name search",
   "Order ID": "Order ID",
   "Dealer name": "Dealer name",
   "Application time": "Application time",
   "Balance of settlement": "Balance of settlement",
   "Settlement amount": "Settlement amount",
   "Administration": "Administration",
   "Payment interface management": "Payment interface management",
   "Payment interface list": "Payment interface list",
   "Add interface": "Add interface",
   "Service provider logo": "Service provider logo",
   "Interface name": "Interface name",
   "ID": "ID",
   "Flow amount": "Flow amount",
   "operation": "operation",
   "List of customer management": "List of customer management",
   "Customer source": "Customer source",
   "Customer ID": "Customer ID",
   "Subordinate site": "Subordinate site",
   "A turnover": "A turnover",
   "integral": "integral",
   "Administrator account": "Administrator account",
   "Select group name": "Select group name",
   "Administrator account search": "Administrator account search",
   "Accounts": "Accounts",
   "Creation Time": "Creation Time",
   "Dealer ID": "Dealer ID",
   "Total goods": "Total goods",
   "Total customer": "Total customer",
   "Total order": "Total order",
   "Total transaction": "Total transaction",
   "Total distribution": "Total distribution",
   "Distributor order totals": "Distributor order totals",
   "Distributor transaction volume": "Distributor transaction volume",
   "Total settlement": "Total settlement",
   "Registration time": "Registration time",
   "Settlement amount to be processed": "Settlement amount to be processed",
   "Site management": "Site management",
   "Choose dealers": "Choose dealers",
   "site": "Site",
   "ChildAccount": "Child Account",
   "MemberManagement": "Member Management",
   "FundManagement": "Fund Management",
   "MarginManagement": "Margin Management",
   "ReCommisManagement": "ReCommis Management",
   "RebateManagement": "RebateManagement",
   "Announcement": "Announcement",
   "SiteChoice": "SiteChoice",
   "UserName": "UserName",
   "DividedManagement": "Divided Management",
   "DealerQuantity": "Dealer Quantity",
   "DivideInto": "DivideInto",
   "CreatePacket": "Create Packet",
   "SortType": "SortType",
   "Enable": "Enable",
   "DealerCommission": "Dealer Commission",
   "DistributorRegistration": "Distributor Registration",
   "Dealer grouping": "Dealer grouping",
   "AdministratorGrouping": "Administrator Grouping",
   "addDelaer": "addDelaer",
   "DistributorName": "Distributor Name",
   "OrderDetails": "Order Details",
   "Check all": "Check all",
   "Batch pass": "Batch pass",
   "Level": "Level",
   "Name": "Name",
   "Balance": "Balance",
   "Reasons for rejection": "Reasons for rejection",
   "Member source": "Member source",
   "distributor": "distributor",
   "Online search": "Online search",
   "Member account": "Member account",
   "Distributors": "Distributors",
   "System balance": "System balance",
   "Online": "Online",
   "Member registration settings": "Member registration settings",
   "members registered": " members registered",
   "Tourist registration": "Tourist registration",
   "Registration requires mailbox": "Registration requires mailbox",
   "Are mailbox repeats allowed": "Are mailbox repeats allowed",
   "Registration requires QQ": "Registration requires QQ",
   "Are you allowed to repeat QQ": "Are you allowed to repeat QQ",
   "Registration requires phone": "Registration requires phone",
   "Are you allowed to repeat phone": "Are you allowed to repeat phone",
   "Registration requires birth date": "Registration requires birth date",
   "Open authentication code": "Open authentication code",
   "Done": "Done",
   "Member order list": "Member order list",
   "Commodity type": "Commodity type",
   "Settlement method": "Settlement method",
   "Order number": "Order number",
   "Order time": "Order time",
   "Transaction amount": "Transaction amount",
   "Purchase amount": "Purchase amount",
   "Add packet": "Add packet",
   "Packet information": "Packet information",
   "Privilege management": "Privilege management",
   "Functional module2": "Functional module2",
   "Function selection": "Function selection",
   "Module enabled": "Module enabled",
   "Create packet completion": "Create packet completion, add administrators to newly created packets in the admin module2, and manage permissions for groups in privilege management.",
   "Create success": "Create success",
   "See": "See",
   "Return list": "Return list",
   "Previous step": "Previous step",
   "Next step": "Next step",
   "Create schedule": "Create schedule",
   "Add Account": "Add Account",
   "accounts": "accounts",
   "Password": "Password",
   "Permission grouping": "Permission grouping",
   "Status enabled disabled": "Status enabled disabled",
   "Enables": "Enable",
   "Disable": "Disable",
   "Confirm": "Confirm",
   "Cancel": "Cancel",
   "Journal": "Journal",
   "Time": "Time",
   "Operation record": "Operation record",
   "Edit account": "Edit account",
   "Submit successfully": "Submit successfully",
   "View grouping": "View grouping",
   "Power": "Power",
   "Total administrator": "Total administrator",
   "Member list": "Member list",
   "Operating time": "Operating time",
   "Grounping": "Grounping",
   "Permission view": "Permission view",
   "Basic information": "Basic information",
   "Confirm password": "Confirm password",
   "Please enter your password again": "Please enter your password again",
   "Divide into groups": "Divide into groups",
   "Modify dealer": "Modify dealer",
   "Confirm submission": "Confirm submission",
   "Modified grouping": "Modified grouping",
   "Enable proxy registration": "Enable proxy registration",
   "Primary dealer": "Primary dealer",
   "Two dealer": "Two dealer",
   "Please enter": "Please enter ",
   "Distributor quantity": "Distributor quantity",
   "Distributor split ratio setting": "Distributor split ratio setting",
   "My ratio": "My ratio",
   "Subordinate ratio": "Subordinate ratio",
   "Packet creation": "Packet creation",
   "Modify": "Modify",
   "Please enter the name of the applicant": "Please enter the name of the applicant",
   "Applicant ID": "Applicant ID",
   "Applicant name": "Applicant name",
   "Subordinate": "Subordinate",
   "CAAC Certificate No": "CAAC Certificate No",
   "Mailbox": "Mailbox",
   "QQ": "QQ",
   "Cell-phone number": "Cell-phone number",
   "Child account list": "Child account list",
   "Unit price": "Unit price",
   "Number of shelves": "Number of shelves",
   "Commission amount": "Commission amount",
   "Inventory quantity": "Inventory quantity",
   "Batch shelves": "Batch shelves",
   "Details": "Details URL",
   "Are goods allowed on shelves": "Are goods allowed on shelves",
   "Release": "Release",
   "(unit: yuan)": "(unit: yuan)",
   "Chinese: apples": "Chinese: apples",
   "(unit: Unit)": "(unit: Unit)",
   "Class A": "Class A",
   "Second level": "Second level",
   "Three": "Three",
   "Commodity details page": "Commodity details page",
   "View details of the goods": "View details of the goods",
   "View commodity information": "View commodity information",
   "Commodity attribute": "Commodity attribute",
   "Publication quantity": "Publication quantity",
   "View categories": "View categories",
   "Classified ID": "Classified ID",
   "Category name": "Category name",
   "Classification description": "Classification description",
   "Add categories": "Add categories",
   "Modify goods": "Modify goods",
   "Site name": "Site name",
   "Site information": "Site information",
   "Tip": "Tip",
   "Select site status": "Select site status",
   "Select the dealer or manually enter the dealer name": "Select the dealer or manually enter the dealer name",
   "PC domain name": "PC domain name",
   "Please enter the PC domain name": "Please enter the PC domain name",
   "WAP domain name": "WAP domain name",
   "Please enter the WAP domain name": "Please enter the WAP domain name",
   "SSI certificate": "SSI certificate",
   "Select file": "Select file",
   "Click Add domain name and certificate customer service information": "Click Add domain name and certificate customer service information",
   "WeChat": "WeChat",
   "Telephone": "Telephone",
   "Email": "Email",
   "Customer service information": "Customer service information",
   "Modify site information": "Modify site information",
   "EditAccount": "Edit Account",
   "EditGroup": "Edit Group",
   "MarginApplication": "Margin application",
   "Order information": "Order information",
   "Commodity information": "Commodity information",
   "Single product discount": "Single product discount",
   "Quantity purchased": "Quantity purchased",
   "Buy discount": "Buy discount",
   "Purchase amount1": "Purchase amount",
   "Operation type": "Operation type",
   "Deposit amount": "Deposit amount",
   "Deposit preferences": "Deposit preferences",
   "Access money": "Access money",
   "Sort": "Sort",
   "Deposit / withdrawal amount": "Deposit / withdrawal amount",
   "Member name": "Member name",
   "Commission list": "Commission list",
   "Commission setting": "Commission setting",
   "Parent account": "Parent account",
   "Recommended number": "Recommended number",
   "Rebate list": "Rebate list",
   "Margin application": "Margin application",
   "Please enter a single number": "Please enter a single number",
   "New application": "New application",
   "Apply for an account": "Apply for an account",
   "Application amount": "Application amount",
   "Date of application": "Date of application",
   "Remittance mode": "Remittance mode",
   "Report details": "Report details",
   "Export EXCEL": "Export EXCEL",
   "User information": "User information",
   "Recharge warning": "Recharge warning",
   "Recharge application": "Recharge application",
   "Recharge alert settings": "Recharge alert settings",
   "Debit note number": "Debit note number",
   "Deductible amount": "Deductible amount",
   "Date of deduction": "Date of deduction",
   "Associated single number": "Associated single number",
   "Third party payment": "Third party payment",
   "Bank card transfer": "Bank card transfer",
   "Bank remittance": "Bank remittance",
   "Remittance form": "Remittance form",
   "Platform name": "Platform ",
   "Girokonto": "Girokonto",
   "Collection account": "Collection account",
   "Transfer amount": "Transfer amount",
   "Transfer time": "Transfer time",
   "Bank name": "Bank name",
   "Transfer card number": "Transfer card number",
   "Collection card number": "Collection card number",
   "Running odd numbers": "Running odd numbers",
   "Rebate amount": "The rebate amount",
   "Set point": "Set point",
   "Check rebate": "Check the rebate",
   "Report form": "Report form",
   "End time": "End time",
   "Today": "Today",
   "Yesterday": "Yesterday",
   "Last week": "Last week",
   "This period": "This period",
   "Number and period in 2016": "Number and period in 2016",
   "Number and period in 2017": "Number and period in 2017",
   "Report type": "Report type",
   "New announcement": "New announcement",
   "Title": "Title",
   "Content": "Content",
   "Release time": "Release time",
   "Publish account": "Publish account",
   "VType": "VType",
   "Dealer account": "Dealer account",
   "Announcement type": "Announcement type",
   "Please select": "Please select",
   "Announcement heading": "Announcement heading",
   "Announcement content": "Announcement content",
   "Subordinate group": "Subordinate group",
   "Recording time": "Recording time",
   "IP address": "IP address",
   "Operation behavior": "Operation behavior",
   "Administrator operation": "Administrator operation",
   "Grade": "Grade",
   "SettlementRequest": "SettlementRequest",
   "DistributorBalance": "DistributorBalance",
   "Account management": "Account management",
   "Distributor list": "Distributor list",
   "Distributor Application List": "Distributor Application List",
   "Distributor application setting": "Distributor application setting",
   "Transaction management": "Transaction management",
   "Goods shelves (dealers)": "Goods shelves (dealers) ",
   "List of goods on shelves": "List of goods on shelves",
   "Rebate settings": "Rebate settings",
   "SystemSettings": "System settings",
   "Member registration management": "Member registration management",
   "Member grouping management": "Member grouping management",
   "Distributor balance view": "Distributor balance view",
   "ReportForm": "ReportForm",
   "A_1": "Member",
   "A_2": "Shareholder",
   "A_3": "General Agent",
   "A_4": "Agent",
   "A_5": "Child Account",
   "A_6": "Member Registration",
   "A_7": "Agency Application",
   "A_8": "System Query",
   "A_9": "Hierarchical",
   "DepositsWithdrawals": "Deposits and withdrawals",
   "HistoryQuery": "History Query",
   "QuotaConversion": "Quota Conversion",
   "MarginReplacement": "Margin replacement record",
   "entryAndExit": "Summary of entry and exit",
   "CashManagement": "Cash Management",
   "MoneyManagement": "Money Management",
   "companyInChina": "company In China",
   "ChinaOnline": "China Online",
   "Immediate": "Immediate audit query",
   "auditLog": "Audit Log",
   "PaymentSetting": "Payment Setting",
   "BankElimination": "Bank Elimination",
   "DepositBankSet": "Deposit Bank Set",
   "IncomeExcludingBank": "Income Excluding Bank",
   "bankElimination": "bank Elimination",
   "OnlinePaymentSetup": "Online Payment Setup",
   "PaymentParameterSetting": "Payment Parameter Setting",
   "AutomaticCashSetting": "Automatic Cash Setting",
   "CashSystem": "Cash System",
   "MemberAnalysis": "Member Analysis",
   "Analysis": "Analysis",
   "MemberInquiries": "Member Inquiries",
   "PurchaseAnalysis": "Purchase Analysis",
   "PreferentialAnalysis": "Preferential Analysis",
   "ValidMembershipList": "Valid MembershipList",
   "CommissionStatistics": "Commission Statistics",
   "AgentRetirementSetting": "Agent Retirement Setting",
   "PeriodManagement": "Period Management",
   "FeeSetting": "Fee Setting",
   "CommissionInquiry": "Commission Inquiry",
   "MemberBalance": "Member Balance",
   "PreferentialCalculation": "Preferential Calculation",
   "SetPreferential": "Set Preferential",
   "PreferentialInquiry": "Preferential Inquiry",
   "PreferentialStatistics": "Preferential Statistics",
   "SelfDefectionQuery": "Self Defection Query",
   "MembershipReturns": "Membership Returns",
   "CommissionSetting": "Commission Setting",
   "RebateSetting": "Rebate Setting",
   "MemberPromotionInquiries": "Member Promotion Inquiries",
   "MemberPromotionSettings": "Member Promotion Settings",
   "QuotaStatistics": "Quota Statistics",
   "RechargeRecord": "Recharge Record",
   "DropList": "Drop List",
   "QuotaRecharge": "Quota Recharge",
   "QuotaRecord": "Quota Record",
   "AnnouncementInformation": "Announcement Information",
   "SystemAnnouncement": "System Announcement",
   "MemberMessage": "Member Message",
   "ReleaseNewMessages": "Release New Messages",
   "RegistrationCouponTemplates": "Registration Coupon Templates",
   "LatestNews": "Latest News",
   "LogManagement": "Log Management",
   "MemberLogin": "Member Login",
   "AdministratorLogin": "Administrator Login",
   "OperationLog": "Operation Log",
   "AutomaticAudit": "Automatic Audit",
   "WebsiteInformation": "Website Information",
   "SiteDataEditor": "Site Data Editor",
   "GraphicEditor": "Graphic Editor",
   "CopyEditor": "Copy Editor",
   "CaseEditor": "Copy Editor",
   "ThePendingCase": "The Pending Case",
   "InThePendingCase": "In The Pending Case",
   "ThroughCase": "Through Case",
   "QuashCase": "Quash Case",
   "Membership details": "Membership details",
   "describe": "describe",
   "Join condition": "Join condition",
   "membership": "membership",
   "Self service return water": "Self service return water",
   "Membership time": "Membership time",
   "Deposit times": "Deposit times",
   "Total deposits": "Total deposits",
   "Member hierarchy": "Member hierarchy",
   "Layered": "Layered",
   "regression": "regression",
   "Payment settings": "Payment settings",
   "Verify that the user is moved to non - hierarchical ?": "Verify that the user is moved to non - hierarchical ?",
   "Hierarchical query": "Hierarchical query",
   "Shareholder": "Shareholder",
   "General agent": "General agent",
   "agent": "agent",
   "Fuzzy query": "Fuzzy query",
   "Serial number": "Serial number",
   "Member": "Member",
   "Registration settings": "Registration settings",
   "Nickname Chinese": "Nickname Chinese",
   "Promotion URL": "Promotion URL",
   "function": "function",
   "New account": "New account",
   "Detailed content": "Detailed content",
   "New proxy account": "New proxy account",
   "Proxy name": "Proxy name",
   "Proxy information": "Proxy information",
   "Proxy account": "Proxy account",
   "Real name": "Real name",
   "English name": "English name",
   "ID number": "ID number",
   "Withdrawal bank": "Withdrawal bank",
   "Bank account": "Bank account",
   "Province": "Province",
   "Counties and cities": "Counties and cities",
   "ATM password": "ATM password",
   "Other promotion methods": "Other promotion methods",
   "Enable Member registration": "Enable Member registration",
   "yes": "yes",
   "No": "No",
   "The date of birth is the indication of whether or not it is hidden": "The date of birth is the indication of whether or not it is hidden",
   "The introducer is said to show, not to hide": "The introducer is said to show, not to hide",
   "The promoters name is show no means hide": "The promoter's name is show, no means hide",
   "Name repetition means permission to repeat": "Name repetition means permission to repeat",
   "Password authentication settings": "Password authentication settings",
   "On-line": "On-line",
   "whole": "whole",
   "Line": "Line",
   "Login account": "Login account",
   "Last logon time": "Last logon time",
   "Finally login to IP": "Finally login to IP",
   "New date": "New date",
   "Landing error times": "Landing error times",
   "current state": "current state",
   "suspend": "suspend",
   "Operation password": "Operation password",
   "Do you need a password": "Do you need a password",
   "Do you want to enable dynamic password settings": "Do you want to enable dynamic password settings",
   "secret key": "secret key",
   "Promote domain names": "Promote domain names",
   "Popularizing ID": "Popularizing ID",
   "Membership": "Membership",
   "Sports accounted for": "Sports accounted for",
   "Lottery accounts for": "Lottery accounts for",
   "Video accounting": "Video accounting",
   "status": "status",
   "Set up": "Set up",
   "data": "data",
   "Discount": "Discount",
   "Domain extension": "Domain extension",
   "General agent name": "General agent name",
   "General agent account number": "General agent account number",
   "Modify the general agent account": "Modify the general agent account",
   "Member registration privilege setting": "Member registration privilege setting",
   "Apply for membership registration privilege": "Apply for membership registration privilege",
   "Discount code": "Discount code",
   "times": "times",
   "Limit IP": "Limit IP",
   "Clear lower level settings": "Clear lower level settings",
   "Shareholder account": "Shareholder account",
   "A_1_1": "Official account",
   "Hidden": "Hidden",
   "source": "source",
   "Registration date": "Registration date",
   "sort": "sort",
   "System quota": "System quota",
   "Video balance": "Video balance",
   "Kick line": "Kick line",
   "Bet": "Bet",
   "cash": "cash",
   "To update": "To update",
   "A_1_2": "Play account",
   "Modify member account": "Modify member account",
   "Can I change the password": "Can I change the password",
   "A_1_3": "Add play",
   "Do you need a mailbox for registration": "Do you need a mailbox for registration",
   "Does registration require WeChat": "Does registration require WeChat",
   "Does registration require documentation": "Does registration require documentation",
   "Do you need a telephone for registration": "Do you need a telephone for registration",
   "Does registration require birthdays": "Does registration require birthdays",
   "enable Member registration": "Enable Member registration",
   "Do you need real names": "Do you need real names",
   "Whether to display the introducer": "Whether to display the introducer",
   "Do you need to fill in the bank card number": "Do you need to fill in the bank card number",
   "Can the phone be repeated": "Can the phone be repeated",
   "Can the mailbox be repeated": "Can the mailbox be repeated",
   "Can QQ repeat": "Can QQ repeat",
   "Can WeChat repeat it": "Can WeChat repeat it",
   "Do you want to open the authentication code": "Do you want to open the authentication code",
   "Membership application amount": "Membership application amount",
   "Code": "Code",
   "Do you want to limit IP": "Do you want to limit IP",
   "Does registration require QQ": "Does registration require QQ",
   "Need": "Need",
   "Unwanted": "Unwanted",
   "Sure": "Sure",
   "May not": "May not",
   "application time": "Application time",
   "Do you want to enable proxy registration settings": "Do you want to enable proxy registration settings",
   "Do you have a Chinese nickname": "Do you have a Chinese nickname",
   "Do you have a English nickname": "Do you have a English nickname",
   "Do you need ID number": "Do you need ID number",
   "Do you need a mailbox": "Do you need a mailbox",
   "Do you need QQ": "Do you need QQ",
   "Do you need phone number": "Do you need phone number",
   "Do you need to promote the URL": "Do you need to promote the URL",
   "Do you need any other methods": "Do you need any other methods",
   "Chinese nickname is required": "Chinese nickname is required",
   "English nickname is required": "English nickname is required",
   "Whether the mailbox is required": "Whether the mailbox is required",
   "Documents are required": "Documents are required",
   "QQ is required": "QQ is required",
   "Mobile phone number is required": "Mobile phone number is required",
   "The URL is required for promotion": "The URL is required for promotion",
   "The other way is required": "The other way is required",
   "Proxy registration settings": "Proxy registration settings",
   "ExitManagement": "ExitManagement",
   "ArtificialWithdrawal": "Artificial Withdrawal",
   "AuditManagement": "Audit Management",
   "PlatformManagement": "Platform Management",
   "CommodityManagement": "Commodity Management",
   "PlatformAccount": "Platform account management",
   "AccountManagement": "Account Management",
   "RoleManagement": "Role Management",
   "MenuManagement": "Menu Management",
   "FunctionManagement": "Function Management",
   "PackageManagement": "Package Management",
   "WebsiteManagement": "Website In for mation",
   "videoManagement": "Video Management",
   "electronicManagement": "Electronic Management",
   "sportManagement": "Sport Management",
   "lotteryManagrment": "Lottery Managrment",
   "modularManagement": "Modular Management",
   "PreferencesSettings": "Preferences Settings",
   "cacheManagement": "Cache Management",
   "LogoManagement": "Logo Management",
   "FloatImg": "Float Img",
   "SwiperImg": "Swiper Img",
   "Notice": "Notice",
   "Advertisement": "Advertisement",
   "GamePic": "GamePic",
   "Upload": "Upload",
   "Attachment": "Attachment",
   "HomeCopy": "Home Copy",
   "DepositCopy": "Deposit Copy",
   "RegisterCopy": "Register Copy",
   "WapDiscount": "WapDiscount",
   "LineDetection": "LineDetection",
   "NewApplication": "NewApplication",
   "screening": "screening",
   "Platformaccount": "Platformaccount",
   "A_10": "account Management",
   "Functionmanagement": "Functionmanagement",
   "Typemanagement": "Typemanagement",
   "configuration": "configuration",
   "Layout Options": "Layout Options",
   "Fixed Header": "Fixed Header",
   "Fixed Navigation": "Fixed Navigation",
   "Fixed Ribbon": "Fixed Ribbon",
   "Fixed Footer": "Fixed Footer",
   "Inside": "Inside",
   "container": "container",
   "RTL": "RTL",
   "Menu on top": "Menu on top",
   "For Colorblind": "For Colorblind",
   "experimental": "experimental",
   "Clear Local storage": "Clear Localstorage",
   "Factory Reset": "Factory Reset",
   "Smart Admin Skins": "Smart Admin Skins",
   "Smart Default": "Smart Default",
   "Dark Elegance": "Dark Elegance",
   "Ultra Light": "Ultra Light",
   "Google Skin": "Google Skin",
   "Pixel Smash": "PixelSmash",
   "Glass": "Glass",
   "Material Design beta": "Material Design beta",
   "success": "success",
   "confirmationOperation": "Whether this operation is confirmed",
   "Red packet management": "Red packet management",
   "Red packet view": "Red packet view",
   "Add red envelopes": "Add red envelopes",
   "Red packet setting": "Red packet setting",
   "Red packet style management": "Red packet style management"
}`
