const data ={
  "Data": {
    "odds": [{
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "0",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#0",
      "id": 0
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#1",
      "id": 1
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#2",
      "id": 2
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#3",
      "id": 3
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#4",
      "id": 4
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#5",
      "id": 5
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#6",
      "id": 6
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#7",
      "id": 7
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#8",
      "id": 8
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#9",
      "id": 9
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#\u5927",
      "id": 10
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#\u5c0f",
      "id": 11
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#\u5355",
      "id": 12
    }, {
      "fc_type": "fc_3d",
      "gameplay": "first_ball",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e00\u7403#\u53cc",
      "id": 13
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "0",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#0",
      "id": 14
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#1",
      "id": 15
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#2",
      "id": 16
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#3",
      "id": 17
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#4",
      "id": 18
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#5",
      "id": 19
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#6",
      "id": 20
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#7",
      "id": 21
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#8",
      "id": 22
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#9",
      "id": 23
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#\u5927",
      "id": 24
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#\u5c0f",
      "id": 25
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#\u5355",
      "id": 26
    }, {
      "fc_type": "fc_3d",
      "gameplay": "second_ball",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e8c\u7403#\u53cc",
      "id": 27
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "0",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#0",
      "id": 28
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "1",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#1",
      "id": 29
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "2",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#2",
      "id": 30
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "3",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#3",
      "id": 31
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "4",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#4",
      "id": 32
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "5",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#5",
      "id": 33
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "6",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#6",
      "id": 34
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "7",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#7",
      "id": 35
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "8",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#8",
      "id": 36
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "9",
      "odd": "9.70",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#9",
      "id": 37
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#\u5927",
      "id": 38
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#\u5c0f",
      "id": 39
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#\u5355",
      "id": 40
    }, {
      "fc_type": "fc_3d",
      "gameplay": "third_ball",
      "input_name": "double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7b2c\u4e09\u7403#\u53cc",
      "id": 41
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "0",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#0",
      "id": 42
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "1",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#1",
      "id": 43
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "2",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#2",
      "id": 44
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "3",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#3",
      "id": 45
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "4",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#4",
      "id": 46
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "5",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#5",
      "id": 47
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "6",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#6",
      "id": 48
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "7",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#7",
      "id": 49
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "8",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#8",
      "id": 50
    }, {
      "fc_type": "fc_3d",
      "gameplay": "gallbladder_ball",
      "input_name": "9",
      "odd": "3.80",
      "pankou": "A",
      "remark": "\u72ec\u80c6#9",
      "id": 51
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "0",
      "odd": "86.00",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#0",
      "id": 52
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "1",
      "odd": "16.70",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#1",
      "id": 53
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "2",
      "odd": "9.40",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#2",
      "id": 54
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "3",
      "odd": "7.20",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#3",
      "id": 55
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "4",
      "odd": "6.20",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#4",
      "id": 56
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "5",
      "odd": "6.00",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#5",
      "id": 57
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "6",
      "odd": "6.20",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#6",
      "id": 58
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "7",
      "odd": "7.20",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#7",
      "id": 59
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "8",
      "odd": "9.40",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#8",
      "id": 60
    }, {
      "fc_type": "fc_3d",
      "gameplay": "span_ball",
      "input_name": "9",
      "odd": "16.70",
      "pankou": "A",
      "remark": "\u8de8\u5ea6#9",
      "id": 61
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "total_sum_big",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u603b\u548c\u5927",
      "id": 62
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "total_sum_small",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u603b\u548c\u5c0f",
      "id": 63
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "total_sum_single",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u603b\u548c\u5355",
      "id": 64
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "total_sum_double",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u603b\u548c\u53cc",
      "id": 65
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "dragon",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u9f99",
      "id": 66
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "tiger",
      "odd": "1.93",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u864e",
      "id": 67
    }, {
      "fc_type": "fc_3d",
      "gameplay": "tiger_ball",
      "input_name": "sum",
      "odd": "9.00",
      "pankou": "A",
      "remark": "\u7e3d\u548c,\u9f8d\u864e#\u548c",
      "id": 68
    }, {
      "fc_type": "fc_3d",
      "gameplay": "triple_ball",
      "input_name": "leopard",
      "odd": "60.00",
      "pankou": "A",
      "remark": "3\u8fde#\u8c79\u5b50",
      "id": 69
    }, {
      "fc_type": "fc_3d",
      "gameplay": "triple_ball",
      "input_name": "straight",
      "odd": "13.00",
      "pankou": "A",
      "remark": "3\u8fde#\u987a\u5b50",
      "id": 70
    }, {
      "fc_type": "fc_3d",
      "gameplay": "triple_ball",
      "input_name": "pairs",
      "odd": "2.80",
      "pankou": "A",
      "remark": "3\u8fde#\u5bf9\u5b50",
      "id": 71
    }, {
      "fc_type": "fc_3d",
      "gameplay": "triple_ball",
      "input_name": "Half_suitable",
      "odd": "2.00",
      "pankou": "A",
      "remark": "3\u8fde#\u534a\u987a",
      "id": 72
    }, {
      "fc_type": "fc_3d",
      "gameplay": "triple_ball",
      "input_name": "Miscellaneous_six",
      "odd": "2.20",
      "pankou": "A",
      "remark": "3\u8fde#\u6742\u516d",
      "id": 73
    }],
    "qishu": "2017315",
    "closetime": {
      "f_t_stro": 6902,
      "k_t_stro": 6932,
      "o_t_stro": 6632,
      "f_state": "2017-11-17 23:56:30",
      "o_state": "2017-11-17 23:52:00",
      "c_time": "2017-11-17 22:01:28",
      "qishu": "179"
    }
  },
  "ErrorCode": 1,
  "ErrorMsg": "\u83b7\u53d6\u6570\u636e\u6210\u529f"
}
export default data;
